### ISSUE TITLE
Add AcrValues property to support IdP

### ISSUE THREAD

**Issue by remcok** [DuendeArchive/IdentityModel.OidcClient#1]
I noticed that there is no option to pass the `acrValues` to the `AuthorizeRequest`.

Extending the `OidcClientOptions` and `AuthorizeState` classes with an `AcrValues` property and gluing it together in the `AuthorizeClient` would provide the ability to use e.g. `idp:Facebook` and bypass the IdSvr login screen and go directly to the provider in question. 
This is very useful when used in native/mobile applications if they present their own set op login options.

**Comment by leastprivilege** [comment]
You can pass extra data as an anonymous object or dictionary.

**Comment by remcok** [comment]
Ok, thanks. I saw that's possible but I just thought it would be more explicit this way since the `CreateAuthorizeUrl` in `AuthorizeRequestExtensions` takes a parameter for it and not to have to deal with adding and naming parameters myself via a _magic_ dictionary. 

Just for the record. So, passing the parameters `loginHint`, `acrValues`, `prompt` (use `OidcConstants.AuthorizeRequest.*` for naming) to `CreateAuthorizeUrl` is done via the `extraParameters` parameter of the `OidcClient.LoginAsync()` method is the preferred way?

**Comment by leastprivilege** [comment]
well - it is the only way right now.

**Comment by remcok** [comment]
Okidoki, clear. Thank you for the feedback. I'll close this issue then.
