### ISSUE TITLE
RedirectURL validation when using UWP

### ISSUE THREAD

**Issue by ncksol** [DuendeArchive/IdentityModel.OidcClient#10]
I was wondering if you could help me with a problem I have. I am trying to build a UWP app that is authenticated through Identity Server.
I've used the UWP sample from this repository as a base. In that sample the redirect url is set through WebAuthenticationBroker.GetCurrentApplicationCallbackUri().
The problem is that my Identity Server has a RedirectUrl validator that verifies that URL supplied with request is the one that the client that is supposed to have (we have different clients for different platforms like web, ios, android etc). But as far as I understand the Uri returned by the method above will be different each time the app is deployed to different computers. Is that so? And if it is, do you know how that can be overcome?
Thanks!

**Comment by ghost** [comment]
I was reading about WebAuthenticatorBroker class here https://docs.microsoft.com/en-us/uwp/api/windows.security.authentication.web.webauthenticationbroker.
I think that the redirectUri generated is like the android schema so if i dont get it wrong yo have to always get the same redirect uri for the specific app, and not by installation of the app.

**Comment by leastprivilege** [comment]
`GetCurrentApplicationCallbackUri()` give you a stable redirect URI for the app. That's what you would configure in IdentityServer.

**Comment by ncksol** [comment]
@leastprivilege oh that's great news! Is there a way to change the URI that is returned via that call? It looks like a random id that is generated when you create the app? Can I get it somehow without calling the method?

**Comment by leastprivilege** [comment]
It is not random. It is based on the app id + the signing cert.
