### ISSUE TITLE
Malformed callback URL

### ISSUE THREAD

**Issue by pmahend1** [DuendeArchive/IdentityModel.OidcClient#107]
```
  at IdentityModel.Client.AuthorizeResponse.ParseRaw () [0x000d3] in C:\local\identity\model\IdentityModel2\src\Client\Messages\AuthorizeResponse.cs:169 
  at IdentityModel.Client.AuthorizeResponse..ctor (System.String raw) [0x00018] in C:\local\identity\model\IdentityModel2\src\Client\Messages\AuthorizeResponse.cs:23 
  at IdentityModel.OidcClient.OidcClient+<ProcessResponseAsync>d__13.MoveNext () [0x000c7] in C:\local\identity\model\OidcClient2\src\OidcClient.cs:173 
--- End of stack trace from previous location where exception was thrown ---
```

The code was working fine but now not. 
I noticed this similar issue when I had upgraded below nugets to above 5.21 but 
```
Microsoft.IdentityModel.Logging
Microsoft.IdentityModel.Tokens
System.IdentityModel.Tokens.Jwt
```

Pls not using latest `IdentityModel(3.10.5)` and `IdentityModel.OidcClient(2.9.0)` nugets.

Since I can not debug inside `OidcClient.cs` / `AuthorizeResponse.cs` of the nuget please help.

**Comment by leastprivilege** [comment]
I doubt that this is related. I would recommend you go to the IdentityModel repo and add some tests for AuthorizeResponse to better understand why it is throwing.

**Comment by FuturistiCoder** [comment]
I have the same issue.
I'm using oidcclient to connect to `https://sts.windows.net/common/v2.0/.well-known/openid-configuration` with `ResponseMode = OidcClientOptions.AuthorizeResponseMode.FormRedirect`
And the first `qparams` in response is this param
`canary=UhMKSFtvW70PNDj3GGrL1NK5BpTxcNeiECbmvcQ7q4c=4`.

From the code source of IdentityModel `AuthorizeResponse.cs`:
```csharp
                var parts = param.Split('=');

                if (parts.Length == 2)
                {
                    Values.Add(parts[0], parts[1]);
                }
                else
                {
                    throw new InvalidOperationException("Malformed callback URL.");
                }
```
but the `parts.Length` equals to 3.

I think `var parts = param.Split('=');` should be changed to `var parts = param.Split('=', 2);`

The workaround is changing `ResponseMode` to `FormPost` for me.

**Comment by leastprivilege** [comment]
Query string parameters must not contain `=` - it seems this canary parameters violates that.

**Comment by DigitApps2** [comment]
ID Porten (Norway) for example - Only S256 is supported. https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Fdifi.github.io%2Fidporten-oidc-dokumentasjon%2Foidc_auth_app.html&sandbox=1
