### ISSUE TITLE
WPF WebViewCompatible + IBrowser + Windows 7 = white screen on login

### ISSUE THREAD

**Issue by JohnGalt1717** [DuendeArchive/IdentityModel.OidcClient#109]
If you use the new WebViewCompatible so that your app uses Edge if on Windows 10 and falls back to IE 11 if it is on Windows 7, and implement it in the IBrowser in WPF, the URL will never execute. It just creates a blank screen.

I can't create any combination or timings of Urls that will fire correctly, even if I put most of the IBrowser inside of a Dispatcher.

Ideas?

**Comment by leastprivilege** [comment]
No sorry.
