### ISSUE TITLE
IdentityServer3 Compatibility

### ISSUE THREAD

**Issue by one-adam-nolan** [DuendeArchive/IdentityModel.OidcClient#11]
Is this library compatible with Identity Server 3?  I was able to successfully use it very quickly with IDS4. However, it is not the case with IDS3.  My current project is a native android / iOS app using Xamarin.   

For client authentication, I am using a Hybrid client and receiving a fragmented redirect.  With ID4, this library works great I can call the following line (taken directly from a sample):
`var result = await _client.ProcessResponseAsync(redirectUrl, _state);`

...and hurray, I get my Identity, Access, and refresh token.  

However, with IDS3, I call the same line and it returns an error of "at_hash missing."  The actual fragmented URI shows the token is there.....It seems this has something to do with extracting the Access Token from the ID Token- but I am not 100% sure. 

Unfortunately, IDS4 is currently out of the question do to some library compatibility issues...so I was hoping to use IDS3 until there is time to properly update the existing libraries to .Net Core.

This leaves my question, is this compatible with IdentityServer3?

Thanks!

**Comment by leastprivilege** [comment]
IdentityServer3 doesn't send the at_hash - you can turn that requirement off on the `OidcClientOptions` class.

**Comment by leastprivilege** [comment]
also https://leastprivilege.com/2017/01/15/platforms-where-you-can-run-identityserver4/

**Comment by one-adam-nolan** [comment]
@leastprivilege Found it on the `Policy` member of the `OidcClientOptions` class and it's working perfectly.  Thank you so much!

**Comment by radu-singer** [comment]
> @leastprivilege Found it on the `Policy` member of the `OidcClientOptions` class and it's working perfectly. Thank you so much!

@one-adam-nolan  Can you please share your xamarin client config on IdSrv3 and the oidcclient options if you still have those. I'm in a similar situation and spent 4days on it with no success
