### ISSUE TITLE
Extend/override ProviderInformation properties fetched during discovery

### ISSUE THREAD

**Issue by mgierlasinskipgs** [DuendeArchive/IdentityModel.OidcClient#110]
Hi, I'm connecting to OpenID server that returns end session endpoint as "logout_endpoint" key in .well-known/openid-configuration json. Because it's not named "end_session_endpoint", client doesn't recognize it as logout endpoint (which is correct). It would be great if there was possibility to manually set some properties from ProviderInvormation after discovery is done. Currently we have to provide full ProviderInvormation object if there is something missing in .well-known/openid-configuration.

**Comment by brockallen** [comment]
Can you ask your vendor to implement the discovery doc according to the spec? I mean, that is the whole point of having a spec...
