### ISSUE TITLE
What exactly is data in client.ProcessResponseAsync(data, state)?

### ISSUE THREAD

**Issue by teejay-87** [DuendeArchive/IdentityModel.OidcClient#113]
What exactly is data in client.ProcessResponseAsync(data, state)?

Also, how am I supposed to mantain OidcClient between two calls to thew web-server?
Can i just instantiate one or have I to instantiate one for each web-site user?

**Comment by teejay-87** [comment]
Doc is very poor, especially for manual mode. All examples are for automatic mode.

**Comment by teejay-87** [comment]
Ok, by trial and error I managed to get it working by passing the RAW request as `data`.

**Comment by leastprivilege** [comment]
data is the URL coming back to the redirect URI

**Comment by leastprivilege** [comment]
Also - this library is not for web apps. It's for native apps like desktop or mobile.

**Comment by teejay-87** [comment]
So there is no C# certified library for web-apps?
Is there no way to use this library for web-apps?

**Comment by leastprivilege** [comment]
ASP.net core has an OIDC client.

**Comment by xperiandri** [comment]
What is the purpose to pass `AuthorizeState` if you need to create the `data` from the properties of state?
I can't figure out any logic.

**Comment by xperiandri** [comment]
Why `AuthorizeClient` is internal?

**Comment by teejay-87** [comment]
> What is the purpose to pass `AuthorizeState` if you need to create the `data` from the properties of state?
> I can't figure out any logic.

Are you talking with me? or the author of library?

**Comment by xperiandri** [comment]
Author

**Comment by teejay-87** [comment]
You should probably open a new issue.

**Comment by CasianArdelean** [comment]
@teejay-87 have you use the manual method? calling Client.ProcessResponseAsync(data, state)?
I would like to see how did you do it because I am stuck, I am getting a nullPointerException in that method when I send 
`var data = $"?state={stateUrl}&nonce={state.Nonce}&code={code}"`

**Comment by teejay-87** [comment]
> @teejay-87 have you use the manual method? calling Client.ProcessResponseAsync(data, state)?
> I would like to see how did you do it because I am stuck, I am getting a nullPointerException in that method when I send
> `var data = $"?state={stateUrl}&nonce={state.Nonce}&code={code}"`

This is what I'm doing now:

When the user presses the "Login with OIDC" button an XMLHttpRequest is made to server:
```
// Generate start URL, state, nonce, code challenge
AuthorizeState authorizeState = this._oidcClient.PrepareLoginAsync().GetAwaiter().GetResult();

this._oidcAuthorizeStates.TryAdd(authorizeState.State, new Tuple<DateTime, AuthorizeState, NameValueCollection>(DateTime.Now, authorizeState, param.Query));

return new PrepareOidcLoginResult { StartUrl = authorizeState.StartUrl };
```
Returned `StartUrl` is passed to frontend and the browser is redirected to that URL.

Then, after returning from external login to my page:
```
if (!this._oidcAuthorizeStates.TryRemove(loginInfo.State, out Tuple<DateTime, AuthorizeState, NameValueCollection> authorizeStateTuple))
{
    retLogin.Result = false;
    retLogin.ErrorMessage = LogonFailureMessage_OidcLoginFailed;
}
else
{
    query = authorizeStateTuple.Item3;

    LoggingHelper.Instance.InfoFormat("Try to create OIDC login session");

    var oidcResult = this._oidcClient.ProcessResponseAsync(loginInfo.Data, authorizeStateTuple.Item2).GetAwaiter().GetResult();
    if (oidcResult.IsError)
    {
        // Login failed

        retLogin.Result = false;
        retLogin.ErrorMessage = LogonFailureMessage_OidcLoginFailed;
    }
    else
    {
        // Login authorized

        string oidcEmail = oidcResult.User.Claims.Single(c => c.Type == "email").Value;
        string oidcSubject = oidcResult.User.Claims.Single(c => c.Type == "sub").Value;

        // ... statements ...
```

**Comment by CasianArdelean** [comment]
@teejay-87 thank you for answer my question.

 What are you doing here? 
`return new PrepareOidcLoginResult { StartUrl = authorizeState.StartUrl };`
After i get the StartUrl i made a ` Response.Redirect(state.StartUrl);` I dont know if is the same.

And here
`var oidcResult = this._oidcClient.ProcessResponseAsync(loginInfo.Data, authorizeStateTuple.Item2).GetAwaiter().GetResult();`

the `authorizeStateTuple.Item2` is the same state as `AuthorizeState authorizeState = this._oidcClient.PrepareLoginAsync().GetAwaiter().GetResult();`? ¿they are the same state?

From my return URL I only get the state and the code ¿ I need more things to create the data to send?

**Comment by teejay-87** [comment]
Yes, `PrepareOidcLoginResult` is basically a "carrier" for data that transits between the application server (IIS) and my login service (console app).

And yes, I had to save all generated authorize states (before login) in:
`ConcurrentDictionary<string, Tuple<DateTime, AuthorizeState, NameValueCollection>> _oidcAuthorizeStates`
 and then retrieve it (after login) with:
`this._oidcAuthorizeStates.TryRemove(loginInfo.State, out Tuple<DateTime, AuthorizeState, NameValueCollection> authorizeStateTuple))`
where `loginInfo.State` is `Request.Form["state"]` (the content of the POST variable `state` coming from extenal login site).

Note that I used `ConcurrentDictionary` with `TryAdd` and `TryRemove` not to have issues with multiple calls in different threads.

**Comment by teejay-87** [comment]
Oh, and `loginInfo.Data` is `Request.Form.ToString()`

**Comment by CasianArdelean** [comment]
okay , buff I don't know, I am still stuck, I think we are doing the same (create `PrepareLoginAsync` do a redirect and get the state and the code) , the only thing different maybe is the `loginInfo.Data`. Can you make a test and tell me what is inside of loginInfo.Data? o maybe is the state, because my state is the same state of the beginning (that with the startUrl).

**Comment by teejay-87** [comment]
Data is `code=........&state=........`
State is the content of the above `state` querystring part (the same returned by `PrepareLoginAsync()` in `State` property).

**Comment by CasianArdelean** [comment]
Okay, @teejay-87 I am going to try again, thank you. I hope this will work
