### ISSUE TITLE
OIDCClient2 hangs when LoginAsync is called for a second time

### ISSUE THREAD

**Issue by PaulBennettTrace** [DuendeArchive/IdentityModel.OidcClient#114]
Hi,

We have a Windows Form with a Chromium Browser and are using OIDCClient2 for logging into our Identity Server. Calling Login.Async for the the first time after application start-up works fine and returns claims, tokens, ...etc as expected. We have a timeout on our session so the Windows Application needs to login again when it times out. In this situation, when calling LoginAsync the thread just seems to hang in the EnsureConfigurationAsync part of the library. The logging is as follows:
[15:11:29 Verbose] IdentityModel.OidcClient.OidcClient
LoginAsync

[15:11:29 Information] IdentityModel.OidcClient.OidcClient
Starting authentication request.

[15:11:29 Verbose] IdentityModel.OidcClient.OidcClient
EnsureProviderInformation

[15:11:29 Debug] IdentityModel.OidcClient.OidcClient
Successfully loaded discovery document

[15:11:29 Debug] IdentityModel.OidcClient.OidcClient
Loaded keyset from "http://localhost:5000/.well-known/openid-configuration/jwks"

[15:11:29 Debug] IdentityModel.OidcClient.OidcClient
Keyset contains the following kids: ["85fccd57b017d6fe12697d741f0cff28"]

There is no output after this, i.e, doesn'tseem to hit the exit point from the async call as there is no log for "Effective options:"

            await EnsureProviderInformationAsync();

            _logger.LogTrace("Effective options:");

Hopefully that makes sense

**Comment by leastprivilege** [comment]
OK - could you do more research for the root cause? I am busy right now.

**Comment by PaulBennettTrace** [comment]
Its OK, it was a threading/async issue which we have resolved. Apologies for the false alarm
