### ISSUE TITLE
LogoutAsync not passing the client_id to the endpoint

### ISSUE THREAD

**Issue by JohnGalt1717** [DuendeArchive/IdentityModel.OidcClient#115]
This is required for many IDPs on the logout with ?client_id=XXX

**Comment by leastprivilege** [comment]
Not in OpenID Connect..

https://openid.net/specs/openid-connect-session-1_0.html#RPLogout

**Comment by JohnGalt1717** [comment]
That makes absolutely no sense if you think about it (and multiple IDPs I've tried against agree with me) because without the clientid (or see below) the IDP will have to log the user out of ALL sessions not just that client.  That would be VERY bad.

Even the documentation you referenced recognizes this: 

"id_token_hint
RECOMMENDED. Previously issued ID Token passed to the logout endpoint as a hint about the End-User's current authenticated session with the Client. This is used as an indication of the identity of the End-User that the RP is requesting be logged out by the OP. The OP need not be listed as an audience of the ID Token when it is used as an id_token_hint value. "

Which is just a variation that is more specific. I'm good with either, but right now id_token_hint isn't set either from what I can tell. (and the id_token of course includes the client_id)

**Comment by brockallen** [comment]
> the IDP will have to log the user out of ALL sessions not just that client. That would be VERY bad.

Can you elaborate?

**Comment by JohnGalt1717** [comment]
If you don't give either the id_token_hint or the client_id as part of the logout, the only information that the IdP will have is the cookie (presumably) to do a logout which might work with implicit flow but even then if you use the built in browser on a phone or even IE in a Desktop app or Edge, you're going to log out the user by cookie which means that EVERYTHING that the user is logged into with that browser will be logged out especially with implicit flow that doesn't handle refresh tokens. 

Hence by not sending this information you're creating a bad user experience at the very least by logging people out everywhere that uses the shared browser, instead of just logging out that specific client (or even better with id_token_hint) the specific client that the user is on.

**Comment by leastprivilege** [comment]
I am not following - first of all client_id is not specified - hence no support for it. If you want support for custom parameters at logout time, well that would be a reasonable feature request.

Besides that - you can't just logout a single client. Logout in OIDC sense means deleting the session at the token service and notifying other clients in the same session that logout occurred.

**Comment by leastprivilege** [comment]
custom params and id_token hint are on the v3 branch IIRC

https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/v3/src/OidcClient.cs#L99

**Comment by JohnGalt1717** [comment]
@leastprivilege Then explain to me how I can, on a windows machine, logout a WPF app using IE 11 as the browser in the app, and have our Web app that runs in IE 11 (Yes I know, just for example purposes) stay logged in.

This is a basic requirement. MS does this all of the time with their OIDC implementation. I can log out of Teams but stay logged in to Chrome even though the teams client is an electron app that shares cookies with Chrome.

What you're suggesting by not passing id_token_hint is a good way to annoy the hell out of users. They want to log out of the client they're in and NOTHING ELSE. If you cause them to log out in other places they will be VERY annoyed. Just ask MS as they're going through fixing their new implementation specifically to fix this mess with Azure especially.

Without id_token_hint you can't "delete the session at the token service and notify other clients in the same session that logout occurred" because you won't know what session you're logging out from because the IdP won't have that information thus it's only option is to log out EVERY client with the same user information by definition of how cookies work.

**Comment by JohnGalt1717** [comment]
If it is implemented, great!

**Comment by brockallen** [comment]
> Then explain to me how I can, on a windows machine, logout a WPF app using IE 11 as the browser in the app, and have our Web app that runs in IE 11 (Yes I know, just for example purposes) stay logged in.

Use the revocation endpoint to revoke your refresh token, then just delete the rest of your tokens that are in-memory and/or in storage. Using a browser to signout will trigger single signout to all the clients, so it sounds like you want to avoid that.

**Comment by brockallen** [comment]
> on a windows machine, logout a WPF app using IE 11 as the browser in the app, and have our Web app that runs in IE 11 (Yes I know, just for example purposes) stay logged in.

Given that using the browser for sign-out will trigger single sign-out, it sounds like you want to avoid that. So from your native app, revoke the refresh token using the revocation endpoint, and then just delete all the tokens you have in storage and/or in-memory.
