### ISSUE TITLE
WinForms WebView & IE Script Error "Object doesn't support property or method 'addEventListener'"

### ISSUE THREAD

**Issue by robertmuehsig** [DuendeArchive/IdentityModel.OidcClient#118]
We currently use the OidcClient version 2.9.0 (running on net472) in combination with IdentityServer4 version 2.4.0 (running on .NET Core 2.2) for our WPF application.

The app and login flow is pretty similar to this [sample application](https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/WinFormsWebView) and we use the same WebView code and - at least a couple of weeks back - everything worked without any issues.

Today I tried to do a normal login and I was greeted with this IE error message:

![image](https://user-images.githubusercontent.com/756703/55827426-6a232700-5b0a-11e9-8bcf-f9dc38337f9e.png)

I looked at the problematic HTML source, which was generated from the IdentityServer4 endpoint (AFAIK this is the [code](https://github.com/IdentityServer/IdentityServer4/blob/5f6371e50e4e08e664e37b2bc3c29d9d96cc6c61/src/IdentityServer4/src/Endpoints/Results/AuthorizeResult.cs#L162) behind the scene]) and the script part is indeed problematic for the default WebBrowserControl powered by IE8 with "<script>window.addEventListener('load', function(){document.forms[0].submit();});</script>".

We found a workaround via setting a registry value for our application under the IE "FEATURE_BROWSER_EMULATION" key.

The strange part is:
I tested the same application under a couple of Windows 10 Version 1803 machines and everything worked as expected - without this registry workaround!
My notebook and another machine running Windows 10 Version 1809 both show the same error. 

Is this a known problem? Has Microsoft changed some IE related stuff with 1809 or was there a "breaking" change within the IdentityServer4? We updated our IdS4 recently to the most recent version, but it seems not to have changed in this area.

(I know that the WebView way is not the preferred way to do this kind of auth flow, but currently we might need to stick with the WebView.)

**Comment by brockallen** [comment]
Perhaps related: https://github.com/IdentityServer/IdentityServer4/issues/3128

**Comment by leastprivilege** [comment]
This is fixed in IdentityServer 2.5
