### ISSUE TITLE
Should bypass error message from Browser to OidcClient

### ISSUE THREAD

**Issue by DzenisevichK** [DuendeArchive/IdentityModel.OidcClient#120]
https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/ed7044f9aa7803c7a3879a64167c6ad49167aaac/src/AuthorizeClient.cs#L67

Should be changed to

`result.Error = browserResult.Error;`

**Comment by leastprivilege** [comment]
thanks - I will have a look.
