### ISSUE TITLE
LogoutAsync: BrowserResult is ignored

### ISSUE THREAD

**Issue by omghb** [DuendeArchive/IdentityModel.OidcClient#123]
### OidcClient.LogoutAsync
When the `IBrowser` implementation returns a `BrowserResult` with an error then this result is ignored.

`LogoutAsync` does not provide a return object (e.g. LogoutResult) and it does not throw an exception. This issue makes troubleshooting with the logout operation difficult.

#### Proposed solution
`LogoutAsync` should throw an exception when the BrowserResult was not `Success`. The result type `UserCancel` should throw an `OperationCanceledException`.

**Comment by KennyDM** [comment]
Hi, 

I noticed the same thing quite some time ago, but I see there was a push changing this behavior on December 9th, 2018. When will this one be available through release (I checked, in 2.9.0 it's not available yet)

Thanks,

**Comment by leastprivilege** [comment]
IIRC it is in the v3 preview.

**Comment by KennyDM** [comment]
Thanks @leastprivilege for the clarification. Do you have any insights on when this will hit GA?

**Comment by leastprivilege** [comment]
soon-ish, But you can try the preview and give feedback

**Comment by codeaphex** [comment]
@leastprivilege : Currently you get a NullReferenceException if you don't provide a LogoutRequest while trying to Logout, you specified a default of 'null' though. Any reason behind this?
![image](https://user-images.githubusercontent.com/39407721/64134883-2c89a800-cde3-11e9-9ab7-a4115e00072e.png)
What kind of advantage do the Request classes provide in general?

**Comment by leastprivilege** [comment]
LogoutRequest provides optional parameters. This sounds like a bug. Can you open a separate issue for that?
