### ISSUE TITLE
Many dependencies from NuGet install

### ISSUE THREAD

**Issue by maritaria** [DuendeArchive/IdentityModel.OidcClient#13]
My target framework is 4.6.1 and I plan to run my project on windows and linux (with mono).
When I try to install the nuget package it also tries to install a lot of dependencies that are already available in the mscorlib. I think this is because it also tries to add .NET core/standard libraries, which I don't need or want because the build output becomes gigantic. I even switched my target to 4.5.2 temporarily but didnt seem to help and .NET standard libraries were still being added.

Is it possible to install this package without so many references being added?

**Comment by leastprivilege** [comment]
That's how netstandard works. We decided to use that technology.
