### ISSUE TITLE
Return result to mobile application when Identity Server throws unauthorized_client

### ISSUE THREAD

**Issue by javaadpatel** [DuendeArchive/IdentityModel.OidcClient#133]
Is there a way to receive a result from the browser (perhaps LoginResult) when there is an exception thrown on the Authorization server? 

Currently, when the app makes a request with invalid credentials then Identity Server returns an error but the user is now stuck on the browser and cancelling the browser tab will be seen as user cancelling not as the actual error which is unauthorized_client.

**Comment by leastprivilege** [comment]
I am confused - you don't send credentials via the browser.

Which exact scenario are you talking about?

**Comment by javaadpatel** [comment]
Admittedly, that was quite a poor description of the problem. The scenario is as below:

Server (implementing Identity Server 4)

 ^
 ||
 ||
 ||
 ^

Mobile Application (implementing OidcClient library. Flow: Authorization code with PKCE)

The mobile application makes a request using `oidcClient.LoginAsync(new LoginRequest())`, this then hits the server which executes the code inside the ClientStore implementation `public async Task<Client> FindClientByIdAsync(string clientId)` but the credentials are not valid (because the client does not exist), so the result of FindClientByIdAsync returns null. 

At this point, the browser then shows an error page saying  "unauthorized_client" but then the user is stuck on this browser page as it does not redirect back to the app. The user then has to manually close the browser but this is seen as a "User Cancelled" result from LoginAsync.

**Comment by leastprivilege** [comment]
Well - there is nothing the client can do about it. IdentityServer deliberately doesn't give control back to the client. 

IOW - you should make the server side error page nicer for end users.

**Comment by javaadpatel** [comment]
That makes sense that identity server does not give control back to the client. 

What would be the best way to handle this kind of situation? Because at this point the client then won't know that it's credentials are in correct since the browser result wouldn't indicate that. 

Our server and client implement dynamic registration, so would it best to perform a back channel request and then receive the error about credentials, forcing the client to re-register, before trying the browser route so that the user wouldn't be stuck in the browser?

**Comment by leastprivilege** [comment]
That could be a possible solution, yes.
