### ISSUE TITLE
"Token" option missing from OidcClientOptions.AuthenticationFlow

### ISSUE THREAD

**Issue by GVirdee** [DuendeArchive/IdentityModel.OidcClient#135]
When using hybrid authentication flow I get an error when trying to retrieve a token, this is using Amazon Cognito. Error: "invalid_request". Error displayed when attempting to load the authorize url. (my guess is that there is an error because Cognito is expecting "token" but is receiving somthing else "code" or "hybrid".

By creating a manual request url, specifying "token" as the "response_type" the UI displays correctly and the app catches the redirect url with the access token included in the response.

Can you add 'token' explicitly as an option for OidcClientOptions.AuthenticationFlow?

**Comment by leastprivilege** [comment]
`token` is not a valid response type for OpenID Connect. Since this is an OIDC library, we don't support it.
