### ISSUE TITLE
How to set 'acr_values' in UWP?

### ISSUE THREAD

**Issue by pellea** [DuendeArchive/IdentityModel.OidcClient#14]
Hello,

Could you point me out how to set the acr_values in UWP?

I found the settings with oidc-client-js but not for the UWP client.
`acr_values: "idp:XXXXXXX"`

Thanks,
Adrien.

**Comment by leastprivilege** [comment]
see https://github.com/IdentityServer/IdentityServer4/issues/937#issuecomment-287690271

**Comment by pellea** [comment]
My bad, I should have searched better.

It's working perfectly. Thx.
