### ISSUE TITLE
Automation of implicit, hybrid, and authorization_code flows (for integration-testing use cases)

### ISSUE THREAD

**Issue by daiplusplus** [DuendeArchive/IdentityModel.OidcClient#147]
A few of my projects use OIDC+OAuth2 and they needed integration tests for various human-user-facing components, which meant that my automated integration tests needed to get tokens that are exactly the same as those as though they used a web-browser (for web-apps) or OS/app browser window popup (for native apps) - so using ROPC is out of the question.

I saw that someone tried to contribute Implicit support back in 2017 ( https://github.com/IdentityModel/IdentityModel.OidcClient2/pull/39 ) but it was rejected - for the fair reason that Implicit shouldn't be used by Native apps - but in my case (and I'm sure for many others) it is very useful to have this functionality available for integration testing purposes.

So I forked the `IdentityModel.OidcClient2` repo and added-in functionality for Implicit and Hybrid authentication - by separating out the human-facing-web-browser tasks (with `OidcClient`'s `IBrowser`) and adding additional `HttpClient` extension methods.

Here's a bird's' eye view of my API:

```
	public interface IIntegrationOidcClient
	{
		Task<FrontChannelAuthorizeResult> LoginAuthorizationCodeFrontChannelAsync( HttpMessageHandler httpMessageHandler, AuthorizationCodeOidcLoginParameters  parameters, CancellationToken cancellationToken = default );
		Task<FrontChannelAuthorizeResult> LoginHybridFrontChannelAsync           ( HttpMessageHandler httpMessageHandler, HybridFrontChannelOidcLoginParameters parameters, CancellationToken cancellationToken = default );
		Task<ImplicitOidcLoginResult>     LoginWithImplicitFlowAsync             ( HttpMessageHandler httpMessageHandler, OidcLoginParameters                   parameters, CancellationToken cancellationToken = default );
	}

	public class FrontChannelAuthorizeResult
	{
		public AuthorizeState State { get; }
		public Boolean IsError { get; }
		public String Error { get; }
		public String BrowserResultType { get; }
		public String Raw { get; }
		public AuthorizeResponse Successful { get; }

		public AuthorizationCodeTokenRequest CreateAuthorizationCodeTokenRequest()
		{
			if( this.IsError ) throw new InvalidOperationException( "This result is invalid." );

			return new AuthorizationCodeTokenRequest()
			{
				Code         = this.Successful.Code ?? throw new InvalidOperationException( "This 'code' is null." ),
				RedirectUri  = this.State.RedirectUri,
				CodeVerifier = this.State.CodeVerifier
			};
		}
	}

	public abstract class OidcLoginParameters<TFlowData>
        {
		public Uri              Authority    { get; }
		public String           ClientId     { get; }
		public String           RedirectUri  { get; }
		public String           Scope        { get; }
		public Boolean          LoadProfile  { get; }

		public abstract OidcResponseMode ResponseMode { get; }
		public abstract String           ResponseType { get; }

		public TFlowData BrowserFlowData { get; } // <-- contains username, password, etc as necessary for the invocation
        }

	public class SimulatedBrowser : IBrowser
	{
		// Wraps a HttpClient / HttpMessageHandler with persistent cookies and auto-redirection support to simulate a basic desktop browser without scripting support
	}

	public abstract class SimulatedBrowserSequence
	{
		Task<BrowserResult> RunAsync( HttpClient httpClient, Uri startUri, Uri endUri, ResponseMode responseMode, TFlowData flowData ) 
	}
        // SimulatedBrowserSequence is then subclassed for my project's own AuthorizationCodeFlow, HybridFlow, and ImplicitFlow actions and performs step-by-step HTTP request/response-handling, including HTML-parsing and form extraction
```

Is this something that could be contributed into `IdentityModel.OidcClient2`?

**Comment by leastprivilege** [comment]
I don't have the cycles right now to think about that. 

I first need to update IdentityModel and IdentityServer - then I will turn my attention to OidcClient again. 

OidcClient is an implementation of the OAuth for native apps spec - so no Implicit flow. Strictly speaking even hybrid flow is not needed.

**Comment by daiplusplus** [comment]
> I don't have the cycles right now to think about that.

No worries - this isn't a priority. My code works for me - I'm just wanting to share it and hopefully make it part of the `IdentityModel` suite.

> OidcClient is an implementation of the OAuth for native apps spec - so no Implicit flow. Strictly speaking even hybrid flow is not needed.

Implicit flow support is necessary for web-applications' automated test infrastructure to acquire an `access_token` to test a web-service without having to jump through the hoops of adding a new client configuration - or for cases where it's a regression-test for a bug that only happened with a specific auth flow (Implicit, Hybrid or Code) - or the worst case: when writing tests for your web-service uses that uses tokens granted by an uncooperative third-party IdP. (My point is that I believe there is a strong, legitimate, need for programs to perform automated authentication).

Correct. Perhaps it could live in a separate project `IdentityModel.OidcTesting` (or `IdentityModel.OAuth2AndOidcTesting` to be more precise)?

**Comment by leastprivilege** [comment]
I agree that such a general purpose library would be useful for many people. 

But OidcClient is an implementation of https://tools.ietf.org/html/rfc8252

If I would need some automated testing for it, I would write an IBrowser that would internally use something like 

https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/test/IdentityServer.IntegrationTests/Common/BrowserClient.cs

So IOW - feel free to use my code and create such a library. I'd be happy to give it a try. But this should live under your account/organization. Not mine.

**Comment by blushingpenguin** [comment]
@Jehoel: i'd be interested in your fork

**Comment by leastprivilege** [comment]
I will close this issue - let me know when you are done with your testing lib
