### ISSUE TITLE
Can we have option to merge few custom claims present in access token obtained from redeeming Authorization code,  in the final Validation result ClaimsPrincipal.

### ISSUE THREAD

**Issue by codding-buddha** [DuendeArchive/IdentityModel.OidcClient#148]
We have permissions claim present in access token obtained during OIDC authorization code flow. This permission claims is used to determine the role of the user. 
It would be good if we have options to merge few claims coming from access token into claims principal or is there any other way I clean way I can do this without actually decoding the access token.

**Comment by leastprivilege** [comment]
Access tokens are for APIs - not for the client. So if the client needs those claims, you need to put them into the identity token.

**Comment by codding-buddha** [comment]
Thanks. Makes sense.
