### ISSUE TITLE
Login with Facebook SDK

### ISSUE THREAD

**Issue by jeetendra18** [DuendeArchive/IdentityModel.OidcClient#15]
Let say I need following 
(1) User click on facebook login of my app
(2) User already login with facebook App in his mobile
(3) I am using facebook SDK to get token
(4) Now I want to store user information and get local access token

Can you please guide , if its supported by Identity Model 4

Thanks

**Comment by leastprivilege** [comment]
You need your own server to achieve

(4) Now I want to store user information and get local access token

to swap the Facebook token with an access token for your API.

IdentityServer4 could do that e.g.
