### ISSUE TITLE
Nuget package missing commits?

### ISSUE THREAD

**Issue by codeaphex** [DuendeArchive/IdentityModel.OidcClient#152]
Like mentioned in #123, I experienced a NullReferenceException when I didn't supply a LogoutRequest object to the LogoutAsync method.
Further investigating the problem I found out that the related code seems to be changed in the master branch https://github.com/IdentityModel/IdentityModel.OidcClient2/commit/33ad609a5073729b87d8228cbeb99f2cf301bcb4 in **Dec 2018**, though I haven't tried using the master directly yet.
I'm using the current nuget preview https://www.nuget.org/packages/IdentityModel.OidcClient/3.0.0-preview.1.15 from **2 months ago**, but they don't seem to include the changes.
![image](https://user-images.githubusercontent.com/39407721/64192734-a5d4d980-ce7b-11e9-895e-437bc3645972.png)

Is there anything wrong with the nuget packaging?

**Comment by leastprivilege** [comment]
I am busy right now updating IdentityServer - will look into OidcClient in the coming weeks.

**Comment by leastprivilege** [comment]
I pushed a new package.
