### ISSUE TITLE
FileLoadException on PrepareLoginAsync

### ISSUE THREAD

**Issue by nobba75** [DuendeArchive/IdentityModel.OidcClient#156]
Hi, I get a FileLoadException when calling PrepareLoginAsync in a WinForms application. I have installed the 3.0.0 preview3 to be able to run against .net 4.7.2. 

I have tried reinstalling nuget packages for the oidc-client but still on this call I get these exceptions:
Exception thrown: 'System.IO.FileLoadException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in IdentityModel.OidcClient.dll

Anyone encountered the same issue or have a suggestion to resolve it?

**Comment by leastprivilege** [comment]
Complete stack trace would be helpful.

**Comment by nobba75** [comment]
Seems to be a threading issue similar to #https://github.com/IdentityModel/IdentityModel.OidcClient/issues/114

Closing this, doesn't seem to have anything to do with oidc-client.
