### ISSUE TITLE
Possible to send user name to login browser?

### ISSUE THREAD

**Issue by nobba75** [DuendeArchive/IdentityModel.OidcClient#158]
Is it possible to send the login-browser a login hint to pre-fill the user name, like in oidc-client-js? I see the extraParameters that can be sent to PrepareLoginAsync method, but I can´t figure out the format for sending the user name.

**Comment by leastprivilege** [comment]
The parameter in OIDC is called `login_hint` - set that in the extra params.

**Comment by nobba75** [comment]
Ooops, tried that at first but received an error, must have been due to some other cause then. But thank you for confirming!
