### ISSUE TITLE
Get signing keys from metadata

### ISSUE THREAD

**Issue by nobba75** [DuendeArchive/IdentityModel.OidcClient#159]
Hi,

in .net it is possible to use the OpenIdConnectConfigurationRetriever to get information from the openid configuration endpoint. Among other things the result contains the Signing Keys that can be used to validate the token.
I know that the oidc-library performs a validation during the login process, but I just want to know if it is possible to get hold of the same signing keys through oidc-client in order to perform manual validation?

**Comment by leastprivilege** [comment]
We are using `DiscoveryClient` internally. And yes - this also returns the key material.
