### ISSUE TITLE
invalid_grant / no description

### ISSUE THREAD

**Issue by carloslinks234** [DuendeArchive/IdentityModel.OidcClient#16]
Hi, I am using the IdentityModel.OidcClient2 Dll for a connection to an OpenId server to get a token after giving the credentials or Authentication via Browser, and I got the the following Error. I checked and try to find something in internet without successful.  I got the error on  var result = await client.ProcessResponseAsync(formData, state); anybody has a hin ?

 var options = new OidcClientOptions {
            LoadProfile = true,
            Authority = _Authority ,
            ClientId = "client",
            ClientSecret = "secret",
            RedirectUri = "http://localhost:5678",
            Scope = "openid profile",
            Flow = OidcClientOptions.AuthenticationFlow.AuthorizationCode ,
            FilterClaims = true

sample: https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/master/ConsoleSystemBrowser/ConsoleSystemBrowser/Program.cs

Many Thanks.
Carlos

**Comment by leastprivilege** [comment]
invalid grant can mean many things. Check the logs of our OIDC provider to see what's really wrong.

**Comment by carloslinks234** [comment]
where can I check the logs? or I have to check the main Project?

**Comment by leastprivilege** [comment]
I don't know which OpenID Connect provider you are using.

**Comment by carloslinks234** [comment]
Provider is "IdentityServer3 OpenID Connect Provider and OAuth 2.0 Authorization Server Framework for ASP.NET 4.x/Katana"

**Comment by leastprivilege** [comment]
https://identityserver.github.io/Documentation/docsv2/configuration/logging.html

**Comment by carloslinks234** [comment]
thanks for those tips, I saw something on internal class ResponseProcessor private async Task<TokenResponse> RedeemCodeAsync(string code, AuthorizeState state), errortype: protocol.

**Comment by leastprivilege** [comment]
invalid grant is coming from the server. Find out why.

**Comment by petteas** [comment]
I also have this problem. I have Provider Identity Server 3. In my logs i get this error:

```
invalid_grant { id: 3001, category: "Endpoints", subjectId: null, name: "Endpoint failure" } { Name: "IdSrvFailureEvent", Id: 801, Scope: "IdAppEvent" }
```

It looks like ProcessResponseAsync in the OidcClient fails when it tries to call the token endpoint. I noticed that OidcClient requires System.IdentityModel.Tokens.Jwt version 5.1.3 while my Identity Server 3 uses version 4.0.3. Could there be any breaking changes from version 4.0.3 to 5.1.3 that makes the call to the token endpoint give the invalid_grant error?

**Comment by leastprivilege** [comment]
Did you enable PKCE for your client in IS3 ? PKCE is mandatory.

**Comment by leastprivilege** [comment]
@petteas that is the event output you are showing - logging output would be more detailed.

**Comment by petteas** [comment]
Setting `Flow = Flows.HybridWithProofKey;` for my client in IS3 made it work. Thanks for your quick response and help @leastprivilege!

**Comment by carloslinks234** [comment]
in relation with my issue, it was something in Server, the person on it gave me another ClientID, und clientsecret. then it worked well

**Comment by wiseman13** [comment]
Quick follow up is there any know issues with IS3 with PKCE running on an IIS farm behind ARR? I am seeing the invalid state error on one set of servers, but not another and I have not figured out if that is related to PKCE or something else.
