### ISSUE TITLE
Identity token is missing on token response. when token was never requested

### ISSUE THREAD

**Issue by Renkas** [DuendeArchive/IdentityModel.OidcClient#160]
When using option `Flow = OidcClientOptions.AuthenticationFlow.AuthorizationCode` I get an error stating: "Identity token is missing on token response.".

But there is no identity token ever requested from the server with this flow.

And as stated in this comment: https://github.com/IdentityModel/IdentityModel.OidcClient/issues/41#issuecomment-345352081 it seems to be intentional. But why?

1. AuthorizationCode flow does not ask for id_token. So client should not expect it.
2. OIDC standard does not state anywhere that it is required. In fact you can use any combination of `response_type` values.

For my usecase I need to use this library as OAuth2 client with PKCE flow. I don't care about id_token in my flow.

**Comment by leastprivilege** [comment]
This is an OIDC library - and in OIDC the `openid` scope is mandatory. This will result in an identity token.

If you don't need the id_token - then throw it away - or use a different library.

**Comment by Renkas** [comment]
Yeah I know now that it's a non issue now (I wasn't consenting openid scope). I'll close this
