### ISSUE TITLE
Error loading discovery document: Error connecting to https://<url>/.well-known/openid-configuration. The SSL connection could not be established

### ISSUE THREAD

**Issue by takthetank** [DuendeArchive/IdentityModel.OidcClient#161]
Hello, I have the following setup:
![image](https://user-images.githubusercontent.com/6099270/66386678-4498ac80-e9cb-11e9-9b7d-d82ca99e1768.png)

A Xamarin.Forms project with v4.2.0.815419 and IdentityModel.OidcClient v2.9.1.
When trying to get identity token I get the following:
Error loading discovery document: Error connecting to https://192.168.100.100:44383/.well-known/openid-configuration. The SSL connection could not be established, see inner exception.. ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. 
---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. 
---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED

I'm using it the same way you have it in IdentityModel.OidcClient.Samples for both Android and iOS.

**Comment by leastprivilege** [comment]
> CERTIFICATE_VERIFY_FAILED

It's an HTTPS problem.

**Comment by takthetank** [comment]
Apparently, and I'm using a self signed certificate for dev purposes, but I had no problem until the latest VS2019 update.
Also, the iOS project works just fine, it's only the Android that throws this error.
FYI: For dev purposes and this cert I'm using the known hack 
ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;

**Comment by takthetank** [comment]
So this seems to occur due to this [https://github.com/xamarin/xamarin-android/issues/3682#issuecomment-536105796](url).
The way to bypass it is to use the OidcClientOptions property BackchannelHandler:
`OidcClientOptions options = new OidcClientOptions();
options.BackchannelHandler = new HttpClientHandler()
{ ServerCertificateCustomValidationCallback = (message, certificate, chain, sslPolicyErrors) => true };`

This works only in Andorid for now, iOS still uses the old `ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;`

**Comment by surensaluka** [comment]
> So this seems to occur due to this [https://github.com/xamarin/xamarin-android/issues/3682#issuecomment-536105796](url).
> The way to bypass it is to use the OidcClientOptions property BackchannelHandler:
> `OidcClientOptions options = new OidcClientOptions(); options.BackchannelHandler = new HttpClientHandler() { ServerCertificateCustomValidationCallback = (message, certificate, chain, sslPolicyErrors) => true };`
> 
> This works only in Andorid for now, iOS still uses the old `ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;`

This works on UWP as well.
