### ISSUE TITLE
Can you verify that the client MUST make sure that authority == document.issuer

### ISSUE THREAD

**Issue by ghstahl** [DuendeArchive/IdentityModel.OidcClient#164]
https://github.com/coreos/go-oidc/issues/219

I have a OIDC endpoint where the {{authority}}/.well-known/openid-configuration produces a [discovery document](https://gist.github.com/ghstahl/7ea35ae28fec7eac49920833798d2e7f).

{{authority}} == "https://localhost:6001"

You will notice that the issuer in the document DOES NOT match identically to the {{authority}}

The coreos/go-oidc codebase doesn't work when it sees this discrepancy, but this codebase does.  

I get that this is all about a replay attack, but I believe I have a use case where {{authority}} != {{issuer}} and have mitigated the replay attack.

**Comment by brockallen** [comment]
https://openid.net/specs/openid-connect-core-1_0.html#IssuerIdentifier

**Comment by ghstahl** [comment]
https://openid.net/specs/openid-connect-core-1_0.html#IssuerIdentifier
I adher to this for my APIs that accept bearer tokens.   This is my impersonation attack mitigation.

I think the thing I am trying to determine  if it is a MUST is the following;
https://openid.net/specs/openid-connect-discovery-1_0.html#Impersonation
It talks about what the RP(client) MUST do.  Which is making sure that the {{authority}} == {{issuer}}, where   {{authority}}/.well-known/openid-configuration produces a discovery document that contains the {{issuer}}.

My assertion is that this really should be a "RECOMMENDATION" vs a "MUST" for the RP.  I have a case where {{authority}} != {{issuer}} and I have mitigated the so-called Impersonation Attacks.  

Right now IdentityModel.OidcClient doesn't do an {{authority}} == {{issuer}} check to use it.  If you decide to add one please make it optional.

**Comment by brockallen** [comment]
>  I adher to this for my APIs that accept bearer tokens. This is my impersonation attack mitigation.

Unrelated -- this is the OIDC spec, which is about id_tokens.
