### ISSUE TITLE
Allow token requests (without openid scope)

### ISSUE THREAD

**Issue by leastprivilege** [DuendeArchive/IdentityModel.OidcClient#167]

**Comment by leastprivilege** [comment]
I think this is done. can't remember...

**Comment by madstt** [comment]
I could use this, is it done or not?

**Comment by leastprivilege** [comment]
Yes

**Comment by madstt** [comment]
Great, is there any samples / documentation on how use this?

**Comment by leastprivilege** [comment]
no :)

**Comment by leastprivilege** [comment]
https://github.com/IdentityModel/IdentityModel.OidcClient/blob/master/test/OidcClient.Tests/CodeFlowResponseTests.cs#L87

**Comment by madstt** [comment]
thanks, I'll try it out...
