### ISSUE TITLE
Add .NET v4.7.2 target for NuGet Package

### ISSUE THREAD

**Issue by lyubomirr** [DuendeArchive/IdentityModel.OidcClient#168]
It is possible to add a v4.7.2 target for the NuGet package because of this issue: https://github.com/dotnet/docs/issues/8896 . Thanks!

**Comment by leastprivilege** [comment]
What exactly is the problem

**Comment by lyubomirr** [comment]
The problem is that a project with target framework 4.7.2 (and later) will use the 4.6.1 libraries from the NuGet package. .NET 4.6.1 is compatible to .NET Standard 1.4 (and earlier) but only partially compatible to .NET Standard 2.0. On the other hand .NET 4.7.2 is fully compatible to .NET Standard 2.0 but not .NET Standard 1.4. This means a lot of assemblies are needed for the host project (like CompilerServices.Unsafe and others) which would not be needed if there was a .NET 4.7.2 version in the NuGet package. The table ".NET implementation support" on https://docs.microsoft.com/en-us/dotnet/standard/net-standard shows this problem under footnote 2.

**Comment by leastprivilege** [comment]
Another option would be to remove the 4.6.1 target. Right?

**Comment by lyubomirr** [comment]
Yes.

**Comment by leastprivilege** [comment]
done.

**Comment by lyubomirr** [comment]
Thanks! :)
