### ISSUE TITLE
Any chance to keep support for .NET 4.5

### ISSUE THREAD

**Issue by pfeigl** [DuendeArchive/IdentityModel.OidcClient#169]
We use IdentityModel.OidcClient in a client application which still compiles against .NET 4.5.2, as we (unfortunately) still have users running on this .NET Framework version.

Since the 3.0 build, you no longer provide an assembly that is compatible with v4.5.2.

Is there any chance, you can easily re-add this or were there specific reasons behind dropping this support?

Thanks,
Philipp

**Comment by leastprivilege** [comment]
No. 4.5 is over. You can still use the 2.x version of OidcClient for that.
