### ISSUE TITLE
RequireIdentityTokenOnRefreshTokenResponse

### ISSUE THREAD

**Issue by josephgardner** [DuendeArchive/IdentityModel.OidcClient#17]
What is the use case for `RequireIdentityTokenOnRefreshTokenResponse`? 

I can't find anything in the oidc connect spec about requesting an ID token as part of the refresh flow. Also, is this supported by IdentityServer3?

**Comment by leastprivilege** [comment]
https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse

> Upon successful validation of the Refresh Token, the response body is the Token Response of Section 3.1.3.3 except that it might not contain an id_token.

**Comment by josephgardner** [comment]
Thanks for the info. I now see the id_token was added in the response from a refresh token request as part of IdentityServer/IdentityServer3#3458
