### ISSUE TITLE
[Question] Keeping session stored in browser for web views

### ISSUE THREAD

**Issue by ryanbuening** [DuendeArchive/IdentityModel.OidcClient#172]
I'm using Xamarin Forms, IdentityServer (OpenID, OAuth2), and this OidcClient library for authentication. The app is successfully logging the user in by opening an ASWebAuthenticationSession browser on iOS and a ChromeCustomTabsBrowser on Android. The user gets logged in and I store their access and refresh tokens to secure storage so I'm able to make API calls.

The issue I'm having is after the user logs in, I have places in the mobile app where I want to open a web view to web apps that are also secured behind IdentityServer. When I open the web view, the user is required to authenticate again.

Is there a way to prevent the user from having to log in again when opening the web view after initial log in?

**Comment by leastprivilege** [comment]
Well - in this case you probably can't use the OS provided browser for login. You need to share the browser between login and your app - or rather the cookie container.

**Comment by ryanbuening** [comment]
Ok. That was kind of where my thought process was. What I tried doing was re-using the dependency injected browser used during login for the protected web apps like so:

```
var browserOptions = new BrowserOptions($"https://example.com/protected/route", "");
await DependencyService.Get<IBrowser>().InvokeAsync(browserOptions, default);
```

This "works" in that I'm not prompted for login, however, in iOS I get the alert prompt: "[AppName] Wants to Use "[url]" to Sign in every time because that is what ASWebAuthenticationSession [does](https://github.com/openid/AppAuth-iOS/issues/177).

One alternative to using ASWebAuthenticationSession is to use SFSafariViewController but I'm not sure if that would work with `IdentityModel.OidcClient.Browser.IBrowser`?

But maybe I'm not understanding how to share the cookies between the login and the app correctly. Do you know of any examples of this?

Thanks.

**Comment by leastprivilege** [comment]
You can't use the `ASWebAuthenticationSession` for browsing application pages.. It is made for login only.

You need to use the Safari view controller. This works with OidcClient - but I can't remember the details - nor do I have a sample.
