### ISSUE TITLE
System.InvalidOperationException: Error loading discovery document: Error connecting to https://accounts.google.com/o/oauth2/v2/auth/.well-known/openid-configuration: Not Found

### ISSUE THREAD

**Issue by ElmellaliMobiArchitects** [DuendeArchive/IdentityModel.OidcClient#177]
can't use authentifiication Facebook & google in :
 - Xamarin Forms v 3.4.0.1008975
 - IdentityModel.OidcClient v 3.12
 i try to use [IdentityModel.OidcClient.Samples](https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/XamarinForms)
with facebook and google but not working  

`System.InvalidOperationException: Error loading discovery document: Error connecting to https://accounts.google.com/o/oauth2/v2/auth?/.well-known/openid-configuration: Bad Request`

**Comment by leastprivilege** [comment]
Facebook is not OIDC compliant. Not sure what the issue is with Google.

**Comment by ElmellaliMobiArchitects** [comment]
i fixed the problem by add the `ProviderInformation ` 

```
ProviderInformation = new ProviderInformation
                {
                    IssuerName = "accounts.google.com",
                    AuthorizeEndpoint = "https://accounts.google.com/o/oauth2/v2/auth",
                    TokenEndpoint = "https://www.googleapis.com/oauth2/v4/token",
                    
                    KeySet = new JsonWebKeySet()
                },
```
