### ISSUE TITLE
problems authenticating with Azure AD

### ISSUE THREAD

**Issue by domze68** [DuendeArchive/IdentityModel.OidcClient#18]
I tried to used it against Azure AD, but no success. I copied the WinForms sample, verified that it worked against the example server, then tried to change OicdClientOptions to match the ones in Azure AD.
I set Authority to https://login.microsoftonline.com/[tenant-id]
But when calling _oidcClient.LoginAsync(DisplayMode.Visible) I get following exception:

Error loading discovery document: Issuer name does not match authority: https://sts.windows.net/[tenant-id]

I'm confused. Is it because of mismatch between login.microsoftonline.net and sts.windows.net?
But this is how it is in Azure AD, the URIs to call are based on the first, but the issuer is the second.
Why does it throw an exception?

**Comment by leastprivilege** [comment]
In that case you need to white list the other authority - or turn off endpoint validation altogether.

You can do that on `OidcClient.Policy.DiscoveryPolicy`

**Comment by domze68** [comment]
Thanks. When I turned off both ValidateEndpoints and ValidateIssuerName I got to the login dialog. I still cannot login though as I'm getting "Unauthorized" error back from OidcClient.LoginAsync and I have no idea why.

**Comment by leastprivilege** [comment]
you can add loggers to the LoggerFactory on the options class. This will give you more info.

**Comment by domze68** [comment]
Thanks a lot for the good pointers. Unfortunately I'm not much wiser after examining the log. 
Seems like I got an Authorize response, and then following happens:

dbug: IdentityModel.OidcClient.IdentityTokenValidator[0]
      Added signing key with kid: z039zdsFuizpBfBVK1Tn25QHYO0
dbug: IdentityModel.OidcClient.IdentityTokenValidator[0]
      Added signing key with kid: 2S4SCVGs8Sg9LS6AqLIq6DpW-g8
trce: IdentityModel.OidcClient.ResponseProcessor[0]
      ValidateNonce
trce: IdentityModel.OidcClient.CryptoHelper[0]
      ValidateHash
trce: IdentityModel.OidcClient.CryptoHelper[0]
      GetMatchingHashAlgorithm
dbug: IdentityModel.OidcClient.CryptoHelper[0]
      Determining matching hash algorithm for RS256
dbug: IdentityModel.OidcClient.CryptoHelper[0]
      SHA256
trce: IdentityModel.OidcClient.ResponseProcessor[0]
      RedeemCodeAsync
fail: IdentityModel.OidcClient.OidcClient[0]
      Unauthorized

**Comment by leastprivilege** [comment]
Well - it fails while redeeming the code - so it fails on the AAD side. Maybe they have more information.

One caveat - OidcClient is designed to work against OpenID Connect spec compliant back-ends. AAD is not spec compliant, that's why they have their own proprietary client lib (ADAL) - so that might be the reason it is not working.

**Comment by domze68** [comment]
Azure AD is a certified OpenID provider since 2015.

**Comment by domze68** [comment]
I managed to get further! Apparently I forgot to add ClientSecret to my OidcClientOptions.
But this time it fails on something else (probably me that forgot something else, but the error message is note very descriptive "at_hash is missing"):

trce: IdentityModel.OidcClient.ResponseProcessor[0]
      ValidateTokenResponse
trce: IdentityModel.OidcClient.IdentityTokenValidator[0]
      Validate
dbug: IdentityModel.OidcClient.IdentityTokenValidator[0]
      Added signing key with kid: a3QN0BZS7s4nN-BdrjbF0Y_LdMM
dbug: IdentityModel.OidcClient.IdentityTokenValidator[0]
      Added signing key with kid: z039zdsFuizpBfBVK1Tn25QHYO0
dbug: IdentityModel.OidcClient.IdentityTokenValidator[0]
      Added signing key with kid: 2S4SCVGs8Sg9LS6AqLIq6DpW-g8
trce: IdentityModel.OidcClient.ResponseProcessor[0]
      ValidateNonce
fail: IdentityModel.OidcClient.OidcClient[0]
      at_hash is missing.

**Comment by leastprivilege** [comment]
no it isn't (only discovery has been certified)

https://openid.net/certification/

**Comment by domze68** [comment]
Solved.
Had to set RequireAccessTokenHash to false.
Thanks a lot for all your help!
