### ISSUE TITLE
Variation in response_type depending on OidcClient version

### ISSUE THREAD

**Issue by Helluva3ngineer** [DuendeArchive/IdentityModel.OidcClient#180]
Hi, this is my first IS4 / OidcClient impl so please be patient with me.  I noticed errors coming back  when invoking the system browser in my Xamarin app.  The implementation is essentially what appears in the demo:
```
var browser = DependencyService.Get<IBrowser>();

            var options = new OidcClientOptions
            {
                Authority = "https://demo.identityserver.io",
                ClientId = "native.hybrid",
                Scope = "openid profile email api offline_access",
                RedirectUri = "xamarinformsclients://callback",
                Browser = browser,

                ResponseMode = OidcClientOptions.AuthorizeResponseMode.Redirect
            };

            _client = new OidcClient(options);
```
Using versions 4.1.1 / 3.1.2 of IdentityModel and IdentityModel.OidcClient, the generated URL is similar to:

> https://demo.identityserver.io/connect/authorize?**response_type=code**&...snip...&code_challenge_method=S256&client_id=native.hybrid&scope=openid%20profile%20email%20api%20offline_access&redirect_uri=myapp%3A%2F%2Fcallback

Using the version specified in the demo (3.9.1 / 2.8.1) the following is generated:

> https://demo.identityserver.io/connect/authorize?**response_type=code%20id_token**&nonce=...

...which works as expected.  In other words in the new version the id_token parameter is missing.  Any tips on configuration to get the working outcome?  For now I have rolled back versions in my app.  Thanks.

**Comment by leastprivilege** [comment]
The default values have changed between 2 and 3. But they produce the same output.

In 4 I dropped hybrid flow in favour of code flow only. Which is the recommended setting. So going forward you should use the code response type.
