### ISSUE TITLE
Xamarin Forms - not receiving callback when authenticating using Touch ID for Apple Single Sign On

### ISSUE THREAD

**Issue by shanukag** [DuendeArchive/IdentityModel.OidcClient#181]
Hi, 

I'm trying to implement Apple Single Sign On for my app using Xamarin Forms. The flow is that when a user tries to login, the OidcClient webview opens up redirecting to Identity Server, where the user can select to login using email address/password or social logins (Eg ; Apple). When logging in through Apple, you can login using Touch ID or apple ID/password. When logging in through apple ID, all is working as expected. User is authenticated in Identity Server, and the app receives the callback and the user can login. 

But when using Touch ID to login to Apple, user is still authenticated correctly on the Identity Server side, but the app/Oidc webview doesn't receive a callback. So the webview stays open. I can click the cancel button in the webview and I'll go back to the login screen, where if I click login again, the webview doesn't open up again, I'm just automatically logged into the app. 

I have looked at the Xamarin Forms sample to implement Oidc client and have implemented accordingly, the issue still remains. 

I'm using ; 

- Xamarin Forms 4.3
- OidcClient 3.1.2

I'm setting the OidcClientOptions as below :

```
var browser = DependencyService.Get<IBrowser>();
var options = new OidcClientOptions
{
    Authority = AppSettings.Authority,
    ClientId = Constants.CLIENT_ID,
    Scope = Constants.SCOPE,
    RedirectUri = {PACKAGE_NAME}://callback,
    Browser = browser,
    ClientSecret = Constants.CLIENT_SECRET,
    ResponseMode = OidcClientOptions.AuthorizeResponseMode.Redirect,
    Flow = OidcClientOptions.AuthenticationFlow.Hybrid
};

var client = new OidcClient(options);
var loginRequest = new LoginRequest();
LoginResult login = await client.LoginAsync(loginRequest);
```

Would be great if someone can shed some light on this.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
