### ISSUE TITLE
dll hell in combination with Microsoft.AspNetCore.SignalR.Client

### ISSUE THREAD

**Issue by godrage** [DuendeArchive/IdentityModel.OidcClient#188]
by using 'Microsoft.AspNetCore.SignalR.Client',
which has dependencies for .net standard and Microsoft.Extensions.Logging (>= 3.1.1) 
you get into dll hell with the Microsoft.Extensions.Logging (2.1.1) from the oidcClient.

we are using serverside .net core, but client side we are stuck with .net framework 4.7.x atm

what would be the suggested way to resolve this? typical dll hell resolve strategies seem sort of misplaced (GAC, strongly nameds, etc.). Is it possible to branch with logging bumped to 3.1.1 ?

**Comment by leastprivilege** [comment]
updated. Will push a new 4.x nuget soon.

**Comment by godrage** [comment]
Thanks,
but for whatever reason i am still getting crashes from OidcClient when I use the 4.0.0-prev2 with Microsoft.AspNetCore.SignalR.Client 3.0.0-3.1.2

Using a Winforms Project targeted to .Net Framework 4.7.2;
IdentityModel 4.1.1;

in VS 2017 it works in both debug and release, but as soon as I build a setup it fails to resolve issues with Microsoft.Extensions.Logging as seen in the event view:

```
Application: CORES_UI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException

Exception Info: System.BadImageFormatException
   at Microsoft.Extensions.Logging.LoggerFactory.RefreshFilters(Microsoft.Extensions.Logging.LoggerFilterOptions)
   at IdentityModel.OidcClient.OidcClientOptions..ctor()
   at CORES_UI.Auth.CORESClient..ctor(CORES_UI.ClientModel.Default.Container ByRef, CORES_UI.ClientModel.User ByRef, CORES_UI.UserInterface.Custom.DataNavigatorController ByRef)
   at CORES_UI.UserInterface.Login.FrmLoginStart..ctor()
   at CORES_UI.Program.Main()
```

**Comment by leastprivilege** [comment]
Don't know. 

![image](https://user-images.githubusercontent.com/1454075/76187686-495dc880-61d6-11ea-805c-9272dedc426d.png)

This is as simple as it can get...

**Comment by godrage** [comment]
Thanks, guess I am waiting till its possible to migrate winforms stabily from .net framework to .net 5 ;)
