### ISSUE TITLE
Where can I see documentation for doing the initial authorize request, where I get a code?

### ISSUE THREAD

**Issue by peterstorm** [DuendeArchive/IdentityModel.OidcClient#191]
Hello!

I'm having trouble using this library to do the intial authorize request, where I have to send some parameters like state, code_challenge, code_method, nounce, etc to receive a callback with a code that I _then_ use to retrive an access token.

Can someone redirect me to an example where this is done?

**Comment by leastprivilege** [comment]
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples

**Comment by peterstorm** [comment]
Thank you!
