### ISSUE TITLE
Client Credentials

### ISSUE THREAD

**Issue by Vaccano** [DuendeArchive/IdentityModel.OidcClient#192]
Does IdentityModel.OidcClient support getting an Access Token via Client Credentials (just a Client ID and Client Secret)

I could probably just code up a HttpClient call to get it, but I worry there is more to it than I anticipate and I will get it wrong.  I would rather use a library made by folks who know what they are doing.

I tried to do it using IdentityModel.OidcClient, but the only OidcClientOptions.AuthenticationFlow options are `AuthorizationCode` and `Hybrid`.  As I understand Client Credentials, is a separate flow.

**Comment by leastprivilege** [comment]
OidcClient is for interactive authentication flow - for client credentials use this

https://identitymodel.readthedocs.io/en/latest/client/token.html#requesting-a-token-using-the-client-credentials-grant-type
