### ISSUE TITLE
ProcessResponseAsync Manually c#

### ISSUE THREAD

**Issue by CasianArdelean** [DuendeArchive/IdentityModel.OidcClient#194]
I have a problem with this method. 
The method PrepareLoginAsync work fine, I get the state and the code when I get the response but when I create the data : 
` var data = $"?state={stateUrl}&code={code}";` 
and excute: 
` result = await oidcClient.ProcessResponseAsync(data, state);`
I recive a nullPointerException

The oidcClient I create is the following 

`       
             var options = new OidcClientOptions()

            { 
                ClientId = "ClientId",
                Scope = "openid",
                RedirectUri = "http://localhost"                
                Flow = OidcClientOptions.AuthenticationFlow.AuthorizationCode  
            };

            var baseUrl = "baseUrl";
            String KeySetString = await getJWKSAsync(baseUrl + "/pf/JWKS");
            var keySet = new JsonWebKeySet(KeySetString)
            var pi = new ProviderInformation();

            pi.AuthorizeEndpoint = baseUrl + "/as/authorization.oauth2";
            //pi.EndSessionEndpoint = baseUrl + "/as/revoke_token.oauth2";
            pi.EndSessionEndpoint = baseUrl + "/idp/startSLO.ping";
            pi.TokenEndpoint = baseUrl + "/as/token.oauth2";           
            pi.IssuerName = "IssuerName";
            pi.UserInfoEndpoint = baseUrl + "/idp/userinfo.openid";
            pi.KeySet = keySet;

            
            options.ProviderInformation = pi;
            options.Policy.RequireAccessTokenHash = false;

          
            var _oidcClient = new OidcClient(options);
            var state = await _oidcClient.PrepareLoginAsync();

            Response.Redirect(state.StartUrl);  
`

I do not know why I have that error. If I try this automatically it works fine but manually I do not know what I am missing

Thank you

**Comment by leastprivilege** [comment]
Stack trace would probably help. Also turn on logging.

https://identitymodel.readthedocs.io/en/latest/native/logging.html

**Comment by CasianArdelean** [comment]
@leastprivilege I try this code : 
`
 var serilog = new Serilog.LoggerConfiguration()
            .MinimumLevel.Verbose()
            .Enrich.FromLogContext()
            .WriteTo.LiterateConsole(outputTemplate: "[{Timestamp:HH:mm:ss} {Level}] {SourceContext}{NewLine}{Message}{NewLine}{Exception}{NewLine}")
            .CreateLogger();

            options.LoggerFactory.AddSerilog(serilog);`

and `options.LoggerFactory.AddSerilog(serilog);` does not have `AddSerilog` and `.WriteTo.LiterateConsole` also  does not exist

**Comment by leastprivilege** [comment]
I think you need to add this as well

https://github.com/serilog/serilog-extensions-hosting

**Comment by CasianArdelean** [comment]
@leastprivilege yes it was that, but I do not see now where is writing, the error I receive is in the middle of the `await `, even in the middle should write a log the serilog?

**Comment by leastprivilege** [comment]
I don't know - that's all I got...

**Comment by CasianArdelean** [comment]
@leastprivilege Finally I can see the log on the debug console, so, looking the log I can see  
the Log reaches the `RedeemCodeAsync `method and there he stops, this is the method : 
`
var tokenResult = await client.RequestAuthorizationCodeTokenAsync(
new AuthorizationCodeTokenRequest
            {
                Address = _options.ProviderInformation.TokenEndpoint,

                ClientId = _options.ClientId,
                ClientSecret = _options.ClientSecret,
                ClientCredentialStyle = _options.TokenClientCredentialStyle,

                Code = code,
                RedirectUri = state.RedirectUri,
                CodeVerifier = state.CodeVerifier,
                Parameters = extraParameters ?? new Dictionary<string, string>()`
I have everything , the only 3 things i do not have are the `Parametersand`  the `CancellationToken`
and the `ClientSecret`

**Comment by CasianArdelean** [comment]
@leastprivilege if I wait for a little to see if the method finish the returned error is different is : 
`
Error redeeming code: the task has been canceled  / no description`

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
