### ISSUE TITLE
LoginAsync fails after update to 3.1.2

### ISSUE THREAD

**Issue by FinHorsley** [DuendeArchive/IdentityModel.OidcClient#196]
_Hopefully this is the right place for this!_

We have just updated from `2.9.0` to `3.1.2`, and the login now fails. Looking into the identityServer logs we are seeing the following

`Invalid grant type for client: "authorization_code"`

We have changed nothing on either the client (iOS), or on IdentityServer4. 

I've compared the `2.9.0` -> `3.1.2` tags on git, but can't see anything obvious that might be causing this. https://github.com/IdentityModel/IdentityModel.OidcClient/compare/97055bd...de3c5ee

### Info
IdentityServer4 version: `2.2.0`
Updated OidcClient version: `3.1.2`
Oidc Flow: `Hybrid on iOS`

### Request Content
This is the content that idSrv receives when making the login request
```
{
  "ClientId": "iOS",
  "ClientName": "iOS App",
  "RedirectUri": "com.<OMITTED>://auth",
  "AllowedRedirectUris": [
    "com.<OMITTED>://auth"
  ],
  "SubjectId": "anonymous",
  "ResponseType": "code",
  "ResponseMode": "query",
  "GrantType": "authorization_code",
  "RequestedScopes": "",
  "State": "4c8cHL5TGl8XETmaw92a",
  "Raw": {
    "response_type": "code",
    "nonce": "i82GNeiwertgfdwe34rGIg",
    "state": "4c8cHL52345TGl8XEmbTp",
    "code_challenge": "EB7LmP9r4Td_uihPAXwqoAN1wZAx",
    "code_challenge_method": "S256",
    "client_id": "iOS",
    "scope": "openid profile api offline_access",
    "redirect_uri": "com.<OMITTED>://auth"
  }
}
```

**Comment by FinHorsley** [comment]
So it looks like a default has changed somewhere, as the default `Flow` is now "authorisation_Code". Setting the `Flow` to `Hybrid` fixed the problem 🎉 

**Before updating** 
Weren't explicitly setting the hybrid flow

```
var options = new OidcClientOptions
{
       Authority = authConfig.Authority,
       ClientId = authConfig.ClientId,

       ... more excluded for brevity
 };
```

**After update**
```
var options = new OidcClientOptions
{
      // Explicitly setting the flow here solved the problem
       Flow = AuthenticationFlow.Hybrid,

       Authority = authConfig.Authority,
       ClientId = authConfig.ClientId,

       ... more excluded for brevity
 };
```

**Comment by leastprivilege** [comment]
That’s correct.

**Comment by FinHorsley** [comment]
Thanks! Out of interest, is there any particular reason why the default value was changed? 🙂

**Comment by leastprivilege** [comment]
I am not recommending hybrid flow anymore. In fact - I removed it altogether in v4.

It is not needed - code flow is the simple implementation and has the same security properties.

**Comment by FinHorsley** [comment]
Is this something worth adding to the [docs](https://identitymodel.readthedocs.io/en/latest/native/overview.html) page? 

### Update
Would it be better to update the IdentityServer4 [Grant Types](http://docs.identityserver.io/en/aspnetcore2/topics/grant_types.html) docs? It gives the following list, but it seems like a lot of these are obsolete now?

>Grant types are a way to specify how a client wants to interact with IdentityServer. The OpenID Connect and OAuth 2 specs define the following grant types:
> - Implicit
> - Authorization code
> - Hybrid
> - Client credentials
> - Resource owner password
> - Device flow
> - Refresh tokens
> - Extension grants

**Comment by leastprivilege** [comment]
You are looking at the wrong version

https://identityserver4.readthedocs.io/en/latest/topics/grant_types.html
