### ISSUE TITLE
Increased visibility for changes coming in 4.0

### ISSUE THREAD

**Issue by FinHorsley** [DuendeArchive/IdentityModel.OidcClient#197]
It would be great if there was some more visibility on the upcoming changes coming in 4.0. Is this something that could be configured as a 4.0 [Project](https://github.com/IdentityModel/IdentityModel.OidcClient/projects)? I can see that there are milestones, but projects seem to offer a more visible place to see changes.

Happy to configure a project, but understand that it requires higher user permissions 🙁

**Comment by leastprivilege** [comment]
That's what milestones are for...

https://github.com/IdentityModel/IdentityModel.OidcClient/milestone/2?closed=1

**Comment by FinHorsley** [comment]
I'd argue that projects board gives more visibility about the state of the release (such as todo/in-progress...); not suggesting removing the milestones, just maybe using them alongside a projects board.

A good example I have seen is [Toggl's release boards](https://github.com/toggl/mobileapp/projects/99)

This is definitely just a nice to have though 🙂

**Comment by leastprivilege** [comment]
I agree - but I don't have the resource to maintain that right now.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
