### ISSUE TITLE
demo native WPF app authenticating with Google errors

### ISSUE THREAD

**Issue by kiwidave72** [DuendeArchive/IdentityModel.OidcClient#198]
Im working on a WPF app that uses identity server for auth.

So far i can get the app to auth when i pass in Username and password. But when i try with google.
Google errors saying it not able to sign me in (see attachment).
Ive noticed that the google sign in UI is different if im trying to sign in as a native app than with a ASP.net app. The ASP.net app shows a more modern UI than what is displayed to the user when signing in with the native WPF app. 

Is this a configuration setting im missing.

![google-signin-error](https://user-images.githubusercontent.com/8468461/76035742-ec6fd180-5f8d-11ea-8a7f-27028a41ee89.jpg)

**Comment by leastprivilege** [comment]
This is probably because WPF uses an old version of IE?

**Comment by sameerdube9** [comment]
You may use this: https://www.essentialobjects.com/Products/WebBrowser/Default.aspx

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
