### ISSUE TITLE
Consider make LoggerFactory settable on OidcClientOptions

### ISSUE THREAD

**Issue by StefanOssendorf** [DuendeArchive/IdentityModel.OidcClient#201]
Hi,

what do you think about making the `LoggerFactory` property on `OidcClientOptions.cs` settable for easier adding of logging.
At the moment you need to add your specific logging library during the creation of the `OidcClientOptions` which somehow feels wrong. It would be easier to just replace the LoggerFactory with the one I get from my DI.

Best Regards
Stefan

**Comment by leastprivilege** [comment]
No objections.

Out of curiosity - how are you using OidcClient with DI?

**Comment by StefanOssendorf** [comment]
I am using it within our own `AuthenticationStateProvider` which points to one of our machines. Each machine has it's own IdentityServer. But since our application is able to connect to different machines I need to dynamically create new OidcClient instances. So I created a factory for that. Hence it's nicer and cleaner that the factory depends on an `ILoggerFactory` instead of hard coding our Serilog-Integration.

Hth Stefan
Ps: I'll make a PR once I got some spare time :-).

**Comment by leastprivilege** [comment]
it's done already.

**Comment by StefanOssendorf** [comment]
Great! Thank you :-)

**Comment by StefH** [comment]
Hello @leastprivilege ,

Can you please apply this fix also to the version 3.1.2 ? I could really use this fix.
