### ISSUE TITLE
Using OidcClient to Show SPA app in C# WebBrowser Control with silent login

### ISSUE THREAD

**Issue by cluidold** [DuendeArchive/IdentityModel.OidcClient#202]
Hi,

I have a .NET Core WebApi project and a Vuejs SPA site. When i open the spa, i will be redirected to the Identity Server 4 for login. After successfull login, i will be redirected back to the spa and can use the site and all functionality.
Now i have to make a WPF App which shows a part of this SPA site in a webbrowser control. The site is shown correctly and also the redirect to identity server and redirect back works well. The only problem is, that i don't want to redirect the user to the login page and back because he already entered username an password in the wpf application.

My question now is following: Is it possible to define a client for displaying the spa page in webbrowser control without the required sign-in flow (maybe something like signin-silent?). 
I also have tested the request of the token for username an password. this works very well and the api would work fine, but i didn't find a way to only send the bearer token to my spa site and use the token instead of redirecting to login again.

I hope i could explain my requirements detailed enough and hope anybody has the answer for my problem.

thanks!

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
