### ISSUE TITLE
IdentityServer3 Without a Secret

### ISSUE THREAD

**Issue by georgeslegros** [DuendeArchive/IdentityModel.OidcClient#207]
Hello, I am trying to get it working with IdentityServer3.

I could get it working fine when I provide the client secret in the `OidcClientOptions` but I would like to avoid that if possible.

If I do not provide the secret, then I get `Error redeeming code: invalid_client / no description`

The client uses the `AuthorizationCodeWithProofKey` flow. I tried with `HybridWithProofKey` with no luck.

Any idea ?

**Comment by brockallen** [comment]
> Hello, I am trying to get it working with IdentityServer3.

IIRC, IS3 always required client secrets.

**Comment by georgeslegros** [comment]
All right then, I was on the right track.
Thanks for the very fast response!
