### ISSUE TITLE
Option to bypass id_token signature verification

### ISSUE THREAD

**Issue by jerriep** [DuendeArchive/IdentityModel.OidcClient#21]
Would it be possible for me to add an option to allow user to disable signature verification for the `id_token`?

We are using `code` flow we want option to be able to turn of signature validation completely.

My idea is to add a new option to `OidcClientOptions` - something like `VerifyIdentityTokenSignature` which defaults to `true`. When set to false, it will set the `RequireSignedTokens` property of the `TokenValidationParameters` to false;

https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/dev/src/IdentityModel.OidcClient/IdentityTokenValidator.cs#L39-L48

This will then bypass signature validation:
https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/dev/src/IdentityModel.OidcClient/IdentityTokenValidator.cs#L155

**Comment by leastprivilege** [comment]
Well - IIRC i do support id_tokens with alg=none if coming via the backchannel already (and 
allowed via policy).

**Comment by leastprivilege** [comment]
https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/dev/src/IdentityModel.OidcClient/IdentityTokenValidator.cs#L68-L81

**Comment by jerriep** [comment]
Yes, but in this case it is a signed token, but I want to explicitly skip signature verification

**Comment by leastprivilege** [comment]
I don't follow.

I don't want to add non spec-compliant, vendor specific edge cases.

**Comment by jerriep** [comment]
OK so this sort of relates to #20 as well

If we use code flow, then the exchange of the code for the `id_token` (and other tokens) happens by POSTing to the `/oauth/token` endpoint over SSL, right? So we can be certain payload was not tampered with and `id_token` which is returned from that endpoint is indeed coming directly from correct source, correct? So it is feasible in this instance to bypass signature verification?

**Comment by jerriep** [comment]
BTW, I am not suggesting to make the library by default unsafe. Still keep the correct defaults, but provide some flexibility to override them

**Comment by leastprivilege** [comment]
> So it is feasible in this instance to bypass signature verification?

What does the spec say?

also

a) why do you want to skip the validation?
b) why don't you then do alg=none?

@woloski

**Comment by jerriep** [comment]
According to spec

> If the ID Token is received via direct communication between the Client and the Token Endpoint (which it is in this flow), the TLS server validation MAY be used to validate the issuer in place of checking the token signature. The Client **MUST** validate the signature of all other ID Tokens according to JWS [JWS] using the algorithm specified in the JWT alg Header Parameter. The Client MUST use the keys provided by the Issuer.

**Comment by jerriep** [comment]
So does

> the TLS server validation MAY be used to validate the issuer in place of checking the token signature.

not mean we can bypass?

**Comment by jerriep** [comment]
Want to bring @hzalaz in on this one as well

**Comment by leastprivilege** [comment]
I still don't understand the motivation - if the token is signed, why do you want to skip validation?

**Comment by jerriep** [comment]
Hi @leastprivilege , apologies for this. I will close this issue.

I discussed it internally with the rest of the team and came to the same conclusion
