### ISSUE TITLE
ConsoleClientWithBrowser exception - system.IO.FileNotFoundException in unknown module

### ISSUE THREAD

**Issue by imbru** [DuendeArchive/IdentityModel.OidcClient#211]
I am trying to rund the ConsoleClientWithBrowser program. But i get an erro

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Unknown Module.
Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Systemet finner ikke angitt fil. occurred

Does anyone have any idea what might cause this issue?

**Comment by leastprivilege** [comment]
no sorry

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
