### ISSUE TITLE
The library misuse the HttpClient objects that result in a memory leak and potential socket exhaustion.

### ISSUE THREAD

**Issue by CarlG12** [DuendeArchive/IdentityModel.OidcClient#212]
In the library, the method CreateClient is used in several places in the code to create HttpClient.

I detected two problems:
1) This class implement IDisposable interface and Dispose method is never called.
2) The HttpClient class is designed to be created once and re-used throughtout the life of the application. Read remarks section in the Microsoft documentation [https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient]. The code creates a new instance every time that a request needs to be executed.

This misuse might create problems in long-running applications like exhausting the number of available sockets.

In the fix, if BackchannelHandler is provided, the library needs to define a way to specify if it shall be disposed or not.

**Comment by leastprivilege** [comment]
Hi, 

thanks for researching this. There is a long, long discussion on how to use HttpClient that spans multiple years now.

I can assure you, that the above potential problems are not real problems for native GUIs (and thats what this library is targeting).

**Comment by CarlG12** [comment]
In my case, it's a problem because the user is driving while the application run. Restart the GUI application might create a physical security problems and user does not necessarily check the screen. So, the HttpClient leak is a potential problem that is easy to fix:
1) use using (var client = x.CreateClient()) when you need to use HttpClient.
2) If BackChannelHandler is provided, instantiate the HttpClient and tell the constructor to not dispose the provided BackChannelHandler.

Uses only one instance of HttpClient is an optional improvement.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by CarlG12** [comment]
I never receive any answer from my comment of April 9th that mention that I think that memory leak shall be fixed.
