### ISSUE TITLE
 Could not load type 'System.Security.Cryptography.ECParameters'

### ISSUE THREAD

**Issue by codestorycooked** [DuendeArchive/IdentityModel.OidcClient#213]
Hi,

When I update my app with IdentityModel.OidcClient with 3.1.2 version which is using .NET 4.6.1, I am able to login but after login I get this error: 

```
Error validating identity token: System.TypeLoadException: Could not load type 'System.Security.Cryptography.ECParameters' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at IdentityModel.OidcClient.IdentityTokenValidator.ValidateSignature(String identityToken, JwtSecurityTokenHandler handler, TokenValidationParameters parameters)
   at IdentityModel.OidcClient.IdentityTokenValidator.<ValidateAsync>d__4.MoveNext()

```

Any thoughts on this?
Let me know.

**Comment by codestorycooked** [comment]
Further on this- I saw when I use 3.1.2 in .NET 4.6.1 it always picks up .netstandard 2.0 version of the library, Ideally, it should pick up .NET 4.6.1 version. When I used 3.1.1, then it pics up .NET 4.6.1 correctly. Is this the bug in the library?

**Comment by leastprivilege** [comment]
Well 

![image](https://user-images.githubusercontent.com/1454075/79190527-d5da5700-7e24-11ea-9cc2-15b6f0947257.png)

It has a 4.6.1 target. Not sure what else to do. Do you?

I am personally fed up with all the multi-targeting problems that I seriously consider to just target netstandard in the future. Maybe it's time to update .NET Framework to a version that's not 5 years old...

**Comment by milescook** [comment]
To save opening a new issue, is this the same root cause as my problem...

In the ValidateSignature method of IdentityTokenValidator, OIDC tries to create a ECDSA object which doesn't support ES256, so I get a 'The method or operation is not implemented.' exception at ECDSA.Create(). A quick google suggests using bouncy castle.... maybe I'll submit a PR for doing just that...?

**Comment by leastprivilege** [comment]
I don't want bouncy castle. If that's not supported on the .NET / Windows version you are using - there's nothing I can / want to do about. 

Feel free to fork the code and make it work for your own purposes.

**Comment by leastprivilege** [comment]
Oh - and being said. Check out the latest preview. I separated JWT validation from the core OidcClient. IOW - you could plugin whatever crypto lib you want.
