### ISSUE TITLE
Missing ConfigureAwait

### ISSUE THREAD

**Issue by terabytesw** [DuendeArchive/IdentityModel.OidcClient#219]
Hi all

I am using the OidcClient in Webforms Framework 4.7.2 app, but I could only make it work by downloading the OidcClient source-code and then adding ConfigureAwait on most of the internal Async methods.

If I use the OidcClient as-is, then the synchronous thread isn't being returned to.

Ex.: OidcClient.PrepareLoginAsync().Result will just break out without returning a result. But if I add ConfigureAwait inside **PrepareLoginAsync**:
await EnsureConfigurationAsync()_.ConfigureAwait(false);_
And add ConfigureAwait inside **EnsureConfigurationAsync**:
await EnsureProviderInformationAsync()_.ConfigureAwait(false);_
Then the result is returned to the working thread.

The same goes for the rest of the Async methods.

**Repro steps**:
1. Create a Webforms 4.7.2 project
2. NuGet the IdentityModel.OidcClient
3. Instantiate a OidcClient with correct config
4. Call ex.: PrepareLoginAsync().Result
5. The thread dies

**Solution or workaround** is to wrap the call in a Task.Run and Wait in your WebForm:
Task.Run(() => { authorizeState = oidcClient.PrepareLoginAsync().Result; }).Wait();

**Comment by leastprivilege** [comment]
Can you reproduce that with this sample?

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/WinFormsWebView

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
