### ISSUE TITLE
prefered language for the login page?

### ISSUE THREAD

**Issue by domze68** [DuendeArchive/IdentityModel.OidcClient#22]
Is there any way to pass prefered language into the LoginAsync method so it will be passed on the call made to the OpenID server? I looked into OidcClientOptions, but couldn't find any language related settings there.

**Comment by leastprivilege** [comment]
you can pass an anon object or dictionary into LoginAsync

**Comment by domze68** [comment]
Yes, I'm sorry, I dismissed that one because I was wrongly assuming that prefered language should be sent in the http headers (Accept-Language), but now I can see that you can specify those as an URL parameter in the request to the OpenID server. Thanks!
