### ISSUE TITLE
WebBrowser question

### ISSUE THREAD

**Issue by juanan** [DuendeArchive/IdentityModel.OidcClient#226]
Hi,

I want to use your library in my ASPNET web app (.NET Framework 4.7.2) but I have doubts about the manual/automatic mode with the system brower.

My SPA is just a web application so I don't have to deal with the browser, user can access from any browser so how could I use your library to call an auth server using code flow with Pkce?

Using oidc-client is quiet simple but using IdentityModel.OidcClient only deals with browser, what misleads me.

Many thanks.

**Comment by leastprivilege** [comment]
It's not made for web apps.

**Comment by juanan** [comment]
Many thanks.
