### ISSUE TITLE
implicit flow? client secret?

### ISSUE THREAD

**Issue by domze68** [DuendeArchive/IdentityModel.OidcClient#23]
Is there a way to get an id token without client secret?
From what I understand, implicit flow would accomplish that, but it seems that only AuthorizationCode and Hybrid are present in the library and none of them seems to work without client secret (result.IdentityToken is null if I don't provide client secret in OidcClientOptions).

**Comment by leastprivilege** [comment]
This library follows the OAuth2 for native apps spec - and yes that means - only code and hybrid flow are supported. Client secrets are not required.

Obviously you need to configure your backend to not require a client secret as well.
