### ISSUE TITLE
Possible to change AccessTokenType with OidcClient?

### ISSUE THREAD

**Issue by TedDancing** [DuendeArchive/IdentityModel.OidcClient#231]
Hi there,

According to the identityserver4 docs, an access token can be self contained or reference:
https://identityserver4.readthedocs.io/en/latest/topics/reference_tokens.html

It is my understanding that if it is reference the token, the api will check the token everytime live with the ids4 server (hopefully meaning that signing out the user will invalidate the token).

*if* correc then it would be worth changing the access token type returned to a reference one but I can't see the options in OidcClientOptions - Am I barking up the wrong tree?

**Comment by leastprivilege** [comment]
That's a per client setting in IdentityServer
