### ISSUE TITLE
Extract State and Nonce while preparing login request.

### ISSUE THREAD

**Issue by Crozin** [DuendeArchive/IdentityModel.OidcClient#233]
I'm using OidcClient to talk to my OIDC provider using authorize_code flow. I'm preparing redirection URI using following code:

```
var client = ...;
var loginHint = "....";
var state = await client.PrepareLoginAsync(new Dictionary<string, string>
{
  [OidcConstants.AuthorizeRequest.Prompt] = OidcConstants.PromptModes.None,
  [OidcConstants.AuthorizeRequest.Request] = await BuildRequestJwtAsync(loginHint)
});

return state.StartUrl;

public Task<string> BuildRequestJwtAsync(string loginHint)
{
    var handler = new JwtSecurityTokenHandler();
    var header = new JwtHeader(new SigningCredentials(new SymmetricSecurityKey(Encoding.ASCII.GetBytes(_options.ClientSecret)), OidcConstants.Algorithms.Symmetric.HS256));
    var request = new JwtSecurityToken(header, new JwtPayload(new []
    {
        new Claim(OidcConstants.AuthorizeRequest.ClientId, _options.ClientId),
        new Claim(OidcConstants.AuthorizeRequest.LoginHint, loginHint)
    }));

    return Task.FromResult(handler.WriteToken(request));
}
```

`Request` is a signed JWT(JWS). So far everything worked just fine, however recently my provider demand that mentioned request JWT object should also contain a `state` property. 

OidcClient generates `state` and `nonce` deeply inside its internal code basically doing `CryptoRandom.CreateUniqueId(16)` for both. There's no possibility to manually instruct what `state` should be used, there's also no possibility to extract generated value prior to JWT signing.

I think `PrepareLoginAsync` could optionally accept pregenerated `state` and `nonce` values.

**Comment by Crozin** [comment]
Actually I think instead of exposing those values it could be better to introduce some sort of switch (enum?) instructing whether or not Request parameter as described https://openid.net/specs/openid-connect-core-1_0.html#JWTRequests should be used or not.

**Comment by leastprivilege** [comment]
Yep - I would like to add support for request objects at some point. Will put it on the backlog.

**Comment by leastprivilege** [comment]
tracked here

https://github.com/IdentityModel/IdentityModel.OidcClient/issues/235
