### ISSUE TITLE
Single-Sign-Out in WinForms application

### ISSUE THREAD

**Issue by nobba75** [DuendeArchive/IdentityModel.OidcClient#237]
The oidc-client-js library has the functionality of session monitoring so that when a user signs out in another client, the library will trigger an event that can be handled to manage signout in the current application as well.

Can this be done in a WinForms application using IdentityModel.OidcClient and if so, do you have some guidance? I can not find anything in the samples.

**Comment by leastprivilege** [comment]
No. They are disconnected from each other after the login.

**Comment by nobba75** [comment]
Ok, thanx for quick reply.
