### ISSUE TITLE
uri callback disabled?

### ISSUE THREAD

**Issue by domze68** [DuendeArchive/IdentityModel.OidcClient#24]
I'm trying to implement an authorization flow.
From what I understood so far I'm supposed to go for the AuthorizationCode flow.

I thought the flow would be like this:
1) The client makes a request to the backend and gets a redirect back
2) I use the redirect information (including callback uri) and call LoginAsync 
3) That call pops up a web browser where I can log in
4) The web browser gets redirected to the callback uri
5) The backend receives the callback and gets id token and sets a session cookie
6) The client can use the session cookie to keep on communicating with the backend

The problem is that I'm looking in the samples in the browser implementation WinFormsWebView and can see that the callback is explicitly canceled in the BeforeNavigate2 event. That means that even though I got authorized by the OpenID provider, my backend has still no idea about it and I have no session cookie.

Why was this callback disabled? Is it because it's just a sample and I have to create my own browser implementation that gos throgh with it, or have I misunderstood something?

**Comment by leastprivilege** [comment]
This is not how it works. No cookies - no session. You would use refresh tokens instead.

Check the spec first
https://tools.ietf.org/html/draft-ietf-oauth-native-apps-10

**Comment by domze68** [comment]
The spec is about OAuth2 - where does OpenID Connect come in? Or are you suggesting I should use OAuth2's access tokens and refresh tokens and shouldn't care about id tokens?
I'm note sure what's Oauth2 and what's OpenID Connect....

**Comment by leastprivilege** [comment]
No you should use OAuth - I prefer "code id_token" aka hybrid flow. But plain code flow is also possible,

**Comment by domze68** [comment]
I wasn't sure about using authentication code flow because specs at http://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth are saying:
"The Authorization Code flow is suitable for Clients that can securely maintain a Client Secret between themselves and the Authorization Server." and I cannot.
At the same time https://tools.ietf.org/html/draft-ietf-oauth-native-apps-10 is saying "it is NOT RECOMMENDED for authorization servers to require client authentication of public native apps clients using a shared secret"
Seems a bit contradictory and confusing, but I guess I'll disable client secret in the AP and go with the authentication code flow.
I know this doesn't have a lot to do with the OidcClient package itself, but I'm grateful for your advice as most of the material I can find is dealing with web apps and there is not much written about native apps.

**Comment by leastprivilege** [comment]
Use hybrid with PKCE.

That's my recommendation.
