### ISSUE TITLE
Skipping signature validation

### ISSUE THREAD

**Issue by leonluc-dev** [DuendeArchive/IdentityModel.OidcClient#241]
Is there a way for the library to skip signature validation of incoming tokens?

Our app connects to multiple OpenId providers for which we use the OidcClient and this works fine.
However, recently one of the new services we have to connect turned out to be a simple OAuth server not fully adhering to the OpenID Connect spec. Because of this the server has no discovery document and doesn't publish its keys anywhere. It just has a simple endpoint that can be called to verify tokens.
I tried to connect to this server using OidcClient (since it was a library we already used and OpenId Connect is built upon OAuth) with the following parameters:

```
var options = new OidcClientOptions()
{
    ProviderInformation = new ProviderInformation()
    {
        AuthorizeEndpoint = "https://omitted-server.com/oauth2/authorize",
        TokenEndpoint = "https://omitted-server.com/oauth2/token",
        IssuerName = "https://omitted-server.com/",
    },
    ClientId = clientId,
    RedirectUri = redirectUri,
    Scope = "profile"
    Browser = new AppBrowser(),
};
```
And while this connects and retrieves a token just fine, the final step of the process, the signature validation, fails due to the absence of the KeySet.
Since there's no way to get the keys (and we have no control over the internals of the authentication server being connected to) is there a way to disable signature verification and have the backend do it? Or would I have to utilize a non-Oidc OAuth library for this purpose?

**Comment by incongruousm** [comment]
The preview version of the library provides the ability to specify a custom token validation so what you're looking for could probably be achieved on version 4.0, but not on the current release.

**Comment by leastprivilege** [comment]
That could work - but ultimately the assumption is that the server is OIDC compliant - hence *OidcClient*...
