### ISSUE TITLE
Request for client-side Blazor sample

### ISSUE THREAD

**Issue by denmitchell** [DuendeArchive/IdentityModel.OidcClient#249]
Although the ASP.NET team is working toward a usable solution that provides a configurable built-in identity server for hosted client-side Blazor (and perhaps other) projects, Microsoft's approach isn't quite working well enough for me in .NET Core 3.1 or .NET 5 RC1.  They appear to be wrapping your JavaScript client in their RemoteAuthenticationService, using web assembly JavaScript interop calls.  Wouldn't it be better to use your OidcClient with client-side hosted Blazor?  If so, it would be helpful to see an example of how it might be used.  Much of it should be straight forward, but an example of an IBrowser implementation that worked with Blazor would be great.  Would it use the Blazor NavigationManager behind the scenes?

**Comment by leastprivilege** [comment]
What’s Blazor?

**Comment by denmitchell** [comment]
Blazor is a Microsoft technology that leverages browser support for the [WebAssembly](https://en.wikipedia.org/wiki/WebAssembly) standard to execute C# code in the browser.  WebAssembly, a standard developed by Microsoft, Google, Apple, and Mozilla (and now maintained by the [World Wide Web Consortium](https://www.w3.org/TR/wasm-core-1/) allows languages other than JavaScript to manipulate the DOM, communicate with remote web servers over HTTP, and otherwise create rich, client-side web applications without plugins such as Adobe Flash and Microsoft Silverlight and without transferring execution to a process outside the browser, as was done with Java Applets.  Among other things, browser support for WebAssembly allows the Common Language Runtime and Java Virtual Machines to run entirely inside the browser at near-native speed in a secure, sandboxed environment.  Currently, all the major browsers, including mobile browsers, support WebAssembly.  WebAssembly is one of the most important new technology standards for web application development – literally and figuratively, a [game-changer](https://github.com/AdrienTorris/awesome-blazor#games).  If you were to create a Blazor example for OidcClient – even if you had to tweak with your code base to make it all work more easily – I’m sure that the [Blazor developer community](https://github.com/AdrienTorris/awesome-blazor) including me, would be grateful.  As a side note, your colleague @brockallen seems to know about Blazor [(Using OAuth and OIDC with Blazor)](https://brockallen.com/2019/01/11/using-oauth-and-oidc-with-blazor/).  If you are interested in what Microsoft is doing with Identity Server and Blazor, you could check out the [recent work](https://github.com/dotnet/aspnetcore/pull/25002) by @javiercn at Microsoft.

**Comment by leastprivilege** [comment]
OK - I never used this before. So if you want to create a sample, please let me know, and I can link to it.
