### ISSUE TITLE
Is it possible to load WinFormsWebView as modal dialog, instead of modal less window?

### ISSUE THREAD

**Issue by vu3maz** [DuendeArchive/IdentityModel.OidcClient#250]
Hi,

I've been using this OidcClient winform sample code in my application and I'd like to load the WinFormsWebView (window) as modal dialog **to prevent user from accessing other view components of the main application**. The current implementation is that it spins off this WinFormsWebView as a modal-less dialog and user ends up with launching it multiple times (by mistake) without noticing it, by clicking on the login button from the main app multiple times. I'd like to stop this from happening by making the Winforms as modal dialog. Looking for your thoughts.

In WinFormsWebView.cs:

public async Task<BrowserResult> InvokeAsync(BrowserOptions options, CancellationToken token = default)
{
    ...
    try
    {
                   form.Controls.Add(browser);
                    browser.Show();

                    form.Show();     //making it "form.ShowDialog" does the job but it prevents further flow.
                    browser.Navigate(options.StartUrl);

                    await signal.WaitAsync(); 
    }
}

**Comment by leastprivilege** [comment]
I guess this would be more of a question for the samples repo...
