### ISSUE TITLE
ClientAssertion support - PR?

### ISSUE THREAD

**Issue by KevinDockx** [DuendeArchive/IdentityModel.OidcClient#251]
Hello,

I recently had to enhance OidcClient so it supports working with client assertions (private key jwt, in my case) for client auth.  It's not a big change, essentially it just means exposing a ClientAssertion property and passing the values to the underlying IdentityModel extension method(s) .  It's up & running on my machine, I'd be happy to provide a PR if you're interested?

**Comment by leastprivilege** [comment]
good idea!

**Comment by KevinDockx** [comment]
Here you go: https://github.com/IdentityModel/IdentityModel.OidcClient/pull/252 :-)
