### ISSUE TITLE
Getting Identity Token on Manual Authorization Flow before the URL redirection

### ISSUE THREAD

**Issue by zugelmm** [DuendeArchive/IdentityModel.OidcClient#254]
Hi,

I am enhancing a WinForms-application that has been running for several years, now an OIDC authentication is mandatory. The problem is that the system does not have any redirection URL, and only the Identification token through the BackChannel  is required.

By sending the first GET Request, I get the Authorization Code successfully. However, by submitting the POST token-Request along with the Authorization headers, I have not been able to obtain the Identification token as response.

Here are some parts of my code, where I have tried many options without achieving the goal

        OidcClientOptions options = new OidcClientOptions
        {
          ClientId = eidParameterDict[NameString.EidClientId],
          Authority = eidParameterDict[NameString.EidAuthorizationEndpointUri],
          RedirectUri = "http://localhost/winforms.client",
          Scope = "openid profile",
          Flow = OidcClientOptions.AuthenticationFlow.AuthorizationCode,
          ProviderInformation = new ProviderInformation
          {
            IssuerName = eidParameterDict[NameString.EidIssuerUri],
            AuthorizeEndpoint = eidParameterDict[NameString.EidAuthorizationEndpointUri],
            TokenEndpoint = eidParameterDict[NameString.EidTokenEndpointUri], // original
            KeySet = new IdentityModel.Jwk.JsonWebKeySet(),
          },
          Browser = new WinFormsWebView(),
         // TokenClientCredentialStyle = ClientCredentialStyle.PostBody,
          FilterClaims = false,
         // ResponseMode = OidcClientOptions.AuthorizeResponseMode.FormPost,
        };

      string json = JsonConvert.SerializeObject(tokenRequest, Formatting.Indented);
      oidcClient.Options.BackchannelHandler = new NetworkHandler(json, HttpStatusCode.OK, tokenRequest);
      oidcClient.Options.ClientSecret = "TestClientSecret";
      oidcClient.Options.TokenClientCredentialStyle = ClientCredentialStyle.AuthorizationHeader;

      var state = await oidcClient.PrepareLoginAsync();
      var data = $"?state={state.State}&nonce={state.Nonce}&code={tokenRequest.Code}";
      var result = await oidcClient.ProcessResponseAsync(data, state);

Best regards and thanks for your support in advance
Melina

**Comment by leastprivilege** [comment]
Sorry - I am too busy right now to follow this.

Is this still a problem?
