### ISSUE TITLE
Alternative for OidcClientOptions.AuthenticationFlow.Hybrid ?

### ISSUE THREAD

**Issue by StefH** [DuendeArchive/IdentityModel.OidcClient#258]
I need to use the older 3.1.2 NuGet in order to get this URL:
`https://MYSERVER/connect/authorize?response_type=code%20id_token&nonce=. . . `
The **code** AND the **id_token** are needed when connecting this specific Oidc server implementation.

Is there a way to get this working in the 4.0.0-preview NuGet ?

**Comment by leastprivilege** [comment]
I removed hybrid flow because it is not the recommended way according to the RFC - it also added a lot of complexity.

Code flow is actually easier.

**Comment by srinivasboddu** [comment]
Hi there
To avoid security issue, I also utilised OidcClientOptions.AuthenticationFlow.AuthorisationCode instead of Hybrid.
But how do I read the id_token using call back  page? Please advise

**Comment by srinivasboddu** [comment]
Prevously, while using the Hybrid flow, my app is reading the id_token value from HttpContext.Current.Params
Because of the changes in Flow to "AuthorisationCode", HttpContext doesnot show any id_token
How do I read the id_token that had redirected from identity server to my client applciation?

**Comment by leastprivilege** [comment]
What exactly is your client application?

This library is designed for native front-end apps like WPF, WinForms, iOS etc..

**Comment by srinivasboddu** [comment]
My client application is asp.net web forms.
During the launch of my application, my app is getting redirecting to identityserver4 to get authentication code
In the callback handler, as I'm loosing the previous session  - could not get the Codeverifier, State to requestAuthorizationTokenByCode. PLease advise

**Comment by leastprivilege** [comment]
This library is designed for native front-end apps like WPF, WinForms, iOS etc - not for WebForms.

Katana (aka Microsoft OWIN) would be the recommended library for WebForms.
