### ISSUE TITLE
symbol files

### ISSUE THREAD

**Issue by markns** [DuendeArchive/IdentityModel.OidcClient#26]
Hi,

Are the symbol files published for this library to any symbol server? I can't find them on nuget.smbsrc.net, srv.symbolsource.org/pdb/MyGet or srv.symbolsource.org/pdb/Public

Thanks, Mark

**Comment by leastprivilege** [comment]
That's actually a good question - I remember that `nuget push` did automatically upload symbols.

We are now using`dotnet nuget push` - how does this behave?

**Comment by markns** [comment]
I'm really no expert with nuget and the associated tools I'm afraid, so can't answer your question. For now, I just compiled the library myself and use the pdb generated. Please feel free to close this if you wish.

As an aside, this seems to be a weakness in the .net ecosystem currently - other fairly widely used projects are also having issues: https://github.com/grpc/grpc/issues/9521

**Comment by leastprivilege** [comment]
Maybe @maartenba knows?

**Comment by maartenba** [comment]
It should push to SymbolSource, but SymbolSource is flaky sometimes.

Alternatives:
* Use MyGet + MyGet's symbols (does need addition of a symbol server in VS - see Feed Details page there)
* Use SourceLink and index the PDB to show sources directly from e.g. GitHub

**Comment by leastprivilege** [comment]
Where does the pdb need to be for nuget push to pick it up automatically?

In the same directory as the nupkg or inside the package?

**Comment by maartenba** [comment]
Just make sure to pack with `-Symbols` switch, will generate a `.nupkg` and a `.symbols.nupkg` in the same folder.

**Comment by leastprivilege** [comment]
Thanks! Updated and symbols published
