### ISSUE TITLE
GetDiscoveryDocument on OidcClient

### ISSUE THREAD

**Issue by patryk-mazur-sinch** [DuendeArchive/IdentityModel.OidcClient#263]
I see that there is no possibility to manually trigger retrieving discovery document on OidcClient. Could e.g. `RefreshDiscoveryDocument` method be added to OidcClient? It would enable us to control retrieving discovery document when needed.

**Comment by leastprivilege** [comment]
IIRC the discovery document is refreshed every time a login is done. Why do you need to trigger this manually?
