### ISSUE TITLE
Using client_assertion instead of client_secret

### ISSUE THREAD

**Issue by yvef** [DuendeArchive/IdentityModel.OidcClient#264]
Hi Everyone.
I'm implementing an authentication flow for a client that uses a certificate instead of a secret. But for that purposes I need to specify client_assertion and client_assertion_type values in post body for a request to the token endpoint.
I couldn't find any related stuff.
So, I can implement it, but why it is not yet implemented?

Thanks

**Comment by leastprivilege** [comment]
https://github.com/IdentityModel/IdentityModel.OidcClient/pull/252

It is. It might not be released yet.

**Comment by yvef** [comment]
Thanks.

**Comment by leastprivilege** [comment]
I just pushed an update.
