### ISSUE TITLE
ErrorDescription for LoginResult is null when response has description value

### ISSUE THREAD

**Issue by leonluc-dev** [DuendeArchive/IdentityModel.OidcClient#268]
OIDC compliant endpoints can return both an `error` (error type) and an `error_description` (error message) value in the result.
4.0.0-preview of OidcClient seemingly added the `error_description `property to the result classes as well.

For some reason however when using `LoginAsync` and the authorization process returns an `error_description` value the `ErrorDescription` property of `LoginResult` is still null.

This issue doesn't occur when refreshing tokens. The `ErrorDescription` property of `RefreshTokenResult` does fill properly when using `RefreshTokenAsync` and an error with an `error_description` value is present in the OIDC response.

**Comment by leonluc-dev** [comment]
I've added propagation for the error_description value and opened pull request #269 containing this bit of code

**Comment by leonluc-dev** [comment]
I've added propagation for the error_description value to the client and opened a pull request (#269)

**Comment by leastprivilege** [comment]
thanks - merged!
