### ISSUE TITLE
Please add IHttpClientFactory support

### ISSUE THREAD

**Issue by JohnGalt1717** [DuendeArchive/IdentityModel.OidcClient#271]
We're now using the excellent management practice of using HostBuilder for all of our clients (Xamarin/Uno). It would be really nice to be able to pass in HttpClient into the OdicClient.  This would allow us to take advantage of IHttpClientFactory.

Edit: This also allows us to use Polly throughout the OidcClient pipeline without having to have OidcClient support polly directly.

**Comment by leastprivilege** [comment]
Will look into it when I have time. Feel free to propose a PR.

**Comment by leastprivilege** [comment]
I added a callback to integrate with arbitrary HTTP client creation strategies - would that help?

https://github.com/IdentityModel/IdentityModel.OidcClient/pull/327

I am closing this issue - feel free to comment on the PR.
