### ISSUE TITLE
Regarding the use of HttpClient

### ISSUE THREAD

**Issue by jonsa** [DuendeArchive/IdentityModel.OidcClient#272]
This is more a question than an issue.

I looked through the source and found [OidcClientOptionsExtensions.cs](https://github.com/IdentityModel/IdentityModel.OidcClient/blob/main/src/OidcClient/Infrastructure/OidcClientOptionsExtensions.cs) that contains a method that creates new instances of `HttpClient` which is pretty much called for every request.

I've read on multiple places that creating a lot of new instances of `HttpClient` is a bad practice. Even [Microsoft's own documentation](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) talks about it.

I read #212 which raised the issue but was dismissed by @leastprivilege by saying that there's been year long discussion regarding the usage of `HttpClient` and that this library is only targeting native GUIs.

From what I can tell by the front page of this repository and the documentation site the supported platforms are
> netstandard2.0
> .NET Framework >= 4.6.1
> .NET Core >= 2.0
> UWP
> Xamarin iOS & Android

But from @leastprivilege comment I'm wondering if I should avoid this library if my target is a Windows device?

It would be interesting to take part of that year long discussion because I haven't seen it mentioned that it's a platform specific issue.

**Comment by leastprivilege** [comment]
The main concern for re-creating HttpClients is exhausting ports because closed instances hold on to the socket for about 2 minutes. This is a concern for server applications with lots of traffic.

Do you think this is also a concern for you?

**Comment by jonsa** [comment]
Thank you for pointing out that it's more a server side issue. I missed that detail entirely. I guess it's not bad practice to use the `HttpClientFactory` in a client scenario but it won't degrade as easily if you don't.
