### ISSUE TITLE
Browser close-window causes hang

### ISSUE THREAD

**Issue by quartexNOR** [DuendeArchive/IdentityModel.OidcClient#275]
Client works well, but there is a curious case where, if the user don't login but instead just closes the browser window -- the await continues forever. 

In my case:
`var obj = await _oidcClient.LoginAsync(null, _tokenSource.Token);`

For some reason, the tokensource.token is never used it seems? I cancel that in a form.close delegate, but it makes no difference, the client is stuck in await and wont let go. I must have tried 20 different ways to try and breaks the await, but no success.

Please issue a fix for this, it is quite urgent. Thank you.

**Comment by leastprivilege** [comment]
Hey, 

not sure what the problem is - this library does not include any browser implementation. So I also don't know those details.

In any case - please feel free to investigate the problem yourself and let me know your findings.

**Comment by quartexNOR** [comment]
The problem was as follows:

We have a form where we initialize the browser (CEF), and that supports the oidc browser interface. All of that works well, no issues with normal login and use.

But, if the user decides to just close the window and ignore the login -- the OIDC client gets stuck in limbo. We found no way of telling the OIDC client that "hey, the browser is gone, just stop the sequence".

Since I posted the first issue, we discovered the cancellationtoken approach (i come from C++ and Delphi so that was new to me) and implemented that - but still it would not exit.

The solution was (that a coworker discovered) that we had to test for OperationCanceledException when we invoked the login task. Without that exception handler, it would simply fail. I found it weird that a normal try/catch (exception e) was not enough - and its not documented anywhere (that i know of) so we spent some time isolating it.

```
        private CancellationTokenSource _loginCancelTokenSource;
        private Task<LoginResult> _loginTask;
```

And further:

```
try {
  res = await _loginTask;
} catch (OperationCanceledException  e) {
  // this has to be here otherwise it wont break free
}
```

Since premature closing of the browser-window can also invoke other exceptions, there is a little list of exception handlers - but the OperationCanceledException had to be present. Without it, the oidc client object has to be ditched and you must create a new instance.

It might be good to underline that in the docs, or have an example of how to neatly cancel a login sequence? Perhaps expose a handy method that cancels the current login sequence in a clean, easy to see and use fashion.

Cheers

**Comment by leastprivilege** [comment]
Where did you add this code - in the core library. or in your `IBrowser` implementation?

**Comment by quartexNOR** [comment]
This is from without our application code where we use the OIDC client. You can pass along a cancelationToken reference as a parameter to most of the OIDC methods. But unless you catch that specific exception, you dont get a clean exit. You have to dump the entire OIDC instance and create a fresh one.


So when we start an authentication procedure, we have:

```
_loginTask = _oidcClient.LoginAsync(null, _loginCancelTokenSource.Token);
try {
  await _loginTask
} catch (OperationCanceledException  e) {
  // this must be here, otherwise invoking the cancelationToken has zero effect
}
```

When someone just close the window and dont bother to complete the login sequence, we pick that up and invoke the cancelationToken we passed as the second parameter. But the OIDC sequence only breaks free if that exception handler is present. Its super strange. A normal try/catch (exception e) should have sufficed, but that is not the case. The OIDC client remains completely in limbo and cannot be used again unless we do the above.

I am of course open for us making some sort of mistake here. The only place i found a reference to this behavior was in a C/C++ implementation using IdentityModel.

I figured others would face the same behavior, so wanted to mention it.

**Comment by leastprivilege** [comment]
OK. Thanks for clarifying.
