### ISSUE TITLE
Console Client Sample - SqlLite causes hard crash

### ISSUE THREAD

**Issue by Richard-Grimmer** [DuendeArchive/IdentityModel.OidcClient#285]
Very strange issue - using the clients/ConsoleClientWithBrowser sample, when login is completed on demo.identityserver.io, the console application consistently throws a NullReferenceException in LoopbackHttpListener.SetResult at ln172;

- ctx.Response.WriteAsync("<h1>You can now return to the application.</h1>");

However, I've taken the code and rejigged it to work in my current project and I'm able to get the auth to work correctly (using my own IDServer4 hosted on Azure)....this is until I add a reference to Microsoft.EntityFrameworkCore.Sqlite 5.0.2, at which point the auth fails in the same way. This happens with either a direct reference via NuGet in the console application itself, or in a project added as a project dependency. 

I'm running under the Debugger in VS2019 16.8.4, and my IDServer4

Note that it appears to be the act of adding the package which triggers the crash.

I appreciate it's a sample, but any ideas would be greatly recieved

**Comment by leastprivilege** [comment]
I've seen concurrency problems with this sample in current .NET versions. I did not have the time yet to investigate.

**Comment by Richard-Grimmer** [comment]
Hi - thanks for the reply. I do understand current pressures etc for the sample, and looking at the behaviour, it does seem as though there's some sort of a threading issue.

I'm more baffled by the version that I have which is working until I add a reference to an unrelated package, both since I'm not sure I understand why it works when the sample doesn't, and more how simply adding the package causes the failure - to be clear, I'm not using anything in the package, as in no code calls any code provided by it, it appears to be the act of adding the package that casuses the issue, removing it reverts my version to a working state. This does make me wonder if one of the packages used by the sample is causing the same behaviour, but that's pretty unlikely IMHO given the limited set of dependencies. 

I had the thought that the package (or one of its dependencies - there are some fairly esoteric ones in the Sqlite domain!) was casuing some sort of namespace collision, and the wrong type was being spun up when one inside the web host was being requested, but as far as I can tell it doesn't seem to be the issue

**Comment by leastprivilege** [comment]
..that's what multi-threading issues are - black magic ;)

This is really an issue for the samples repo.
