### ISSUE TITLE
Force fresh login and setting the language

### ISSUE THREAD

**Issue by ArchieCoder** [DuendeArchive/IdentityModel.OidcClient#287]
Hello,

If you don't know, there is a Windows bug/design decision that even if you uninstall a WinRT/UWP app, the browser keeps the cookies.

My team discovered that the spec has "https://openid.net/specs/openid-connect-core-1_0.html" prompt=login.

What is the way to pass this value to the OidcClientOptions class?

I have the same question for setting the language "ui_locales" (https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)

Thank you!

**Comment by NiSHoW** [comment]
I don't know if that's your case but you can pass the parameters like that 

```csharp
 var result = await oidcClient.LoginAsync(new LoginRequest()
{
                FrontChannelExtraParameters = new Dictionary<string, string>()
                {
                    { "prompt",  "login"}
                }
});
```

**Comment by ArchieCoder** [comment]
@NiSHoW Yes, I forgot about my question. I did find it. Thanks
