### ISSUE TITLE
OidcClient 4 stable release

### ISSUE THREAD

**Issue by frederikprijck** [DuendeArchive/IdentityModel.OidcClient#289]
Hello,

First of all, thanks for the work on this awesome OidcClient for .NET.
We are still using 3.x but are looking to come up with a plan to move towards OidcClient 4, mainly because we would like to be able to add a custom IDTokenValidator, which if I am correct is only available in 4.x.

However, as we prefer to use a non-preview version, I was wondering if there is any information available of when we could expect the OidcClient 4 to leave preview and be released as a stable version?

Not trying to put pressure here or anything, just trying to get an understanding of the release schedule so we can see if we can adapt accordingly.

Thanks!

**Comment by leastprivilege** [comment]
There is no schedule right now. Working on it whenever I have time.

You could give it a try and tell me if it works for all your use cases. This would be helpful for me.

**Comment by natelaff** [comment]
Working just fine for me in WinForms. (But I'm not using a custom validator)

**Comment by frederikprijck** [comment]
It has worked fine for us as well, but I believe our use cases are rather limited so definitely didnt validate all bits and pieces.

**Comment by frederikprijck** [comment]
Closing this as it got released!
