### ISSUE TITLE
Issue with malformed URL

### ISSUE THREAD

**Issue by ksevery** [DuendeArchive/IdentityModel.OidcClient#29]
Hello,

I'm currently trying to use this library in order to authenticate from my Xamarin.Android app. The problem I am having is that, after checking out the samples and trying to setup the client on my side, I get a Malformed URL exception. As far as I saw, the issue is that after authentication passes through in the System Browser implementation from the samples, I try to pass in only the callbackUrl, but only the old OIDC client works with this implementation. The new one apparently expects the whole URL with all of the query parameters. 

As I'm quite new to identity servers and Oauth2 and so on, I guess I need some help and maybe ask you to review the samples so they actually work with OidcClient2. Could you shed some light as to what I might do to actually get this to work? I've been trying to handle it on my own for a while, but I'm lacking a lot of knowledge.

Best regards.

**Comment by leastprivilege** [comment]
I am not sure I follow - did you do some more investigation to find the real problem?

**Comment by ksevery** [comment]
Hey, I resolved the issue with a bit of a ... workaround. So, what was happening was that first, I wasn't setting the Authentication Mode to Redirect, but rather left it to the default value (FormPost). I changed that, and afterwards I changed my logic a bit so that the URL that is passed as a result via the BrowserResult was the proper URL containing all of the needed parts - the nonce, the authentication code and everything else. So, I've resolved this on my side, but it would still be very nice if you could look through the Samples linked in the project's description, or I could do a Pull Request there with the changes I made after upgrading to OidcClient2 - just so the samples actually work with the current version.

**Comment by leastprivilege** [comment]
I just merged a PR for the the Android sample. Maybe this is what you are looking for.

But glad you got it figured out.
