### ISSUE TITLE
v4.0 IdentityTokenValidator default behaviour

### ISSUE THREAD

**Issue by leonluc-dev** [DuendeArchive/IdentityModel.OidcClient#291]
I've been testing out the preview versions of v4.0 for a while, and while most of it works perfectly fine I had a question regarding a change to identity token validation behaviour. 

In v3.x the default behaviour was standard signature validation for the identity token unless `options.Policy.RequireIdentityTokenSignature = false;` was set.

v4.0 supports custom identity token validators but not assigning one results in a crash (unless `RequireIdentityTokenSignature` is set to false). The default token validation now requires a separate NuGet package and explicit declaration of the validator (ex: `options.IdentityTokenValidator = new JwtHandlerIdentityTokenValidator();`). 

Is there any specific reason why this was done since it seems like a weird extra requirement for previously default behaviour? It seems to make more sense to have the validator default to the previous behaviour if no custom validator is set rather than a crash and subsequent package + assignment requirement.

**Comment by leastprivilege** [comment]
With code flow, id_token validation is not needed anymore. If you want to validate the token, plug-in your favourite library. The base package doesn't need that mandatory dependency.

**Comment by leonluc-dev** [comment]
I see. Thanks for the information!
