### ISSUE TITLE
Browser close-window causes hang

### ISSUE THREAD

**Issue by FredBesterwitch** [DuendeArchive/IdentityModel.OidcClient#293]
Guys,

any fix for this?

TIA

**Comment by parthasarathiu** [comment]
I'm also facing this issue in Xamarin Android but iOS works as expected.
In Android, when I click the ‘X’ icon in the login web page, it keeps on hanging and unable to proceed further.
Any fix/work around for this issue?

**Comment by dubstepadii** [comment]
I just did something like that
![image](https://user-images.githubusercontent.com/38531657/123758896-0c847c00-d8c8-11eb-8ca1-18519bcf864c.png)
and after wards in activity 
![image](https://user-images.githubusercontent.com/38531657/123759112-45bcec00-d8c8-11eb-8ced-39ffdbc1ca71.png)
did that trick with close button and also with native back.
