### ISSUE TITLE
TokenClientFactory and support for Proof of Possession

### ISSUE THREAD

**Issue by thecontrarycat** [DuendeArchive/IdentityModel.OidcClient#31]
RedeemCodeAsync uses the TokenClientFactory to get a `TokenClient` which it then uses to get an Access Token by calling `RequestAuthorizationCodeAsync`.

According to https://identityserver.github.io/Documentation/docsv2/pop/requesting.html it would be possible to use Proof of Possession if we could convert this call to `RequestAuthorizationCodePopAsync`.  We could add the key to the OidcOptions class, and if it is supplied, use the PoP method instead of the normal one.

Is this something you'd be interested in receiving a PR for?

**Comment by brockallen** [comment]
The PoP spec seems to have lost steam in the OAuth WG. They seem to now favor the HTTP binding specs as an alternative/replacement.

**Comment by thecontrarycat** [comment]
That's annoying.  I'm being asked by our security team to prevent access_tokens from being used by anything other than the original device.  Is there any supported way to do this with Identity Server 3 or 4?  Does the ID3 implementation of PoP work or is it vulnerable in some way?

**Comment by leastprivilege** [comment]
The IS3 implementation of PoP works - but is based on the specs around 1,5 years ago. There are also client libs/validation middleware in the IdentityModel org.

We didn't spend more time with that given the state of the specs. Feel free to use our code.
