### ISSUE TITLE
Sample for WinUI 3

### ISSUE THREAD

**Issue by MarkBQE** [DuendeArchive/IdentityModel.OidcClient#311]
It would be great if we can have a sample for WinUI 3. Any plans for adding one in the near future.

**Comment by leastprivilege** [comment]
Good idea. I don't know anything about WinUI. Feel free to create one and send me the link. Thanks!

**Comment by MarkBQE** [comment]
I will try to create one when I am up to speed with WinUI 3 :), not there yet. It is very early days for WinUI, not sure if we will adopt it for any real world projects. I thought you may already have a sample in works,  nothing urgent.

**Comment by leastprivilege** [comment]
OK. Let me know once you think it is relevant enough to use your own time ;)
