### ISSUE TITLE
 iOS OS Lower Version Support Details (10 & 11)

### ISSUE THREAD

**Issue by MohanOIDC** [DuendeArchive/IdentityModel.OidcClient#316]
Hi Team,

Do OIDC support the backward compatibility for iOS OS Version 10 & 11?. When we are loading our URL, we are not receiving any response from the OIDC server. Please share us the solution to support the older version (10 & 11).

var browser = DependencyService.Get<IBrowser>();
var options = new OidcClientOptions
{
Authority = Constants.AUTHORITY_URL,
ClientId = Constants.CLIENT_ID,
Scope = Constants.SCOPE,
RedirectUri = Constants.REDIRECT_URI,
PostLogoutRedirectUri = Constants.REDIRECT_URI,
ClientSecret = Constants.CLIENT_SECRET,
Flow = OidcClientOptions.AuthenticationFlow.AuthorizationCode,
ResponseMode = OidcClientOptions.AuthorizeResponseMode.Redirect,
Browser = browser,
};
_client = new OidcClient(options);
CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();
var token = cancellationTokenSource.Token;
_result = await _client.LoginAsync(new LoginRequest(), token);

Please share your suggestion and comments  on the above mentioned issue.

Regards
Mohan. S

**Comment by leastprivilege** [comment]
closing. no answers
