### ISSUE TITLE
How to set Flow and ResponseMode in 4.0.0

### ISSUE THREAD

**Issue by eblade** [DuendeArchive/IdentityModel.OidcClient#318]
This may be a stupid question, but since the `Flow` and `ResponseMode`properties have disappeared from the `OidcClientOptions` class in 4.0.0, how do I do to use `AuthorizationCode` and `Redirect` respectively?

**Comment by leastprivilege** [comment]
It will always use the two values you mentioned ;)

**Comment by eblade** [comment]
Thank you @leastprivilege ! That's perfect :)
