### ISSUE TITLE
Build for Release platform target limited to Any CPU

### ISSUE THREAD

**Issue by sergiosolorzano** [DuendeArchive/IdentityModel.OidcClient#319]
Hi, I have a question please. 

I am trying to build main branch project with VS2019 for Release x86 and I'm finding I can only set to x86 ConsoleClientWithProject and OidcClient.

The rest I can only set to Any CPU. I'm showing on this snapshot trying to edit OidcClient.Tests, only choice is Any CPU.

Is that how this project, only a few can be built for x86 or a problem on my end?

https://drive.google.com/file/d/1qiVE1tIrP6cTBgeIW59s46ouBEM5g5cD/view?usp=sharing

Thanks!

**Comment by leastprivilege** [comment]
closing. no answers.
