### ISSUE TITLE
HTTPS Requirements?

### ISSUE THREAD

**Issue by MikeEsteves** [DuendeArchive/IdentityModel.OidcClient#32]
Does this require the Identity Server to be running over https with a valid cert or can that be turned off when developing locally?

Thanks

**Comment by leastprivilege** [comment]
That can be turned off.

**Comment by MikeEsteves** [comment]
What's the OidcClientOptions' option? Or how do you go about turning it off?

**Comment by leastprivilege** [comment]
There are discovery options on it. It should be pretty self-explaining.

**Comment by MikeEsteves** [comment]
Nevermind, WebAuthenticationOptions has to have a https address to work. That's my issue. Will use the system browser instead. Is there an example with the system browser instead of wab browser for uwp?

**Comment by roblapp** [comment]
Here is how to disable HTTPS requirements (only use for development purposes)

```
var options = new OidcClientOptions
              {
                  Policy = new Policy
                  {
                           Discovery = new DiscoveryPolicy
                                             {
                                                  RequireHttps = false
                                             }
                   }
              };
```
