### ISSUE TITLE
Is it possible to get code_verifier in IdentityModel.OidcClient?

### ISSUE THREAD

**Issue by sergiosolorzano** [DuendeArchive/IdentityModel.OidcClient#321]
Hi, oidcclient sends the request with the code_challenge already generated. I am [testing on postman to get the token once I have the auth code](https://docs.microsoft.com/en-us/azure/active-directory-b2c/authorization-code-flow#2-get-an-access-token), where can I get the code_verifier oidcclient used to generate the code_challenge? 

Thank you

**Comment by leastprivilege** [comment]
You can call `PrepareLogin` which returns 

https://github.com/IdentityModel/IdentityModel.OidcClient/blob/main/src/OidcClient/AuthorizeState.cs

**Comment by sergiosolorzano** [comment]
Closing the question, thank you for your help @leastprivilege
