### ISSUE TITLE
Setting ResponseMode as OidcClientOptions.AuthorizeResponseMode.FormPost in v4.X

### ISSUE THREAD

**Issue by maurelio1234** [DuendeArchive/IdentityModel.OidcClient#325]
Hi, do you have some docs on migrating from 3.x to 4.x?
I see a coupe of issues with individual changes (like https://github.com/IdentityModel/IdentityModel.OidcClient/issues/318) but I can't find any more comprehensive doc on what changed and why.

In particular I had this in my Oidc options:

`            var options = new OidcClientOptions
            {
                ...
                ResponseMode = OidcClientOptions.AuthorizeResponseMode.FormPost
            };
`

And obviously this doesn't even compile any more.
What is the replacement?
Are there any other changes I need to care about when migrating?

Thanks in advance

**Comment by leastprivilege** [comment]
I removed hybrid and form-post in favour of staying closer to the RFC.

The only flow supported now is authorization code with the query response type.
