### ISSUE TITLE
When run the ConsoleClientWithBrowser project in master branch, throw an exception here.

### ISSUE THREAD

**Issue by jason-shi** [DuendeArchive/IdentityModel.OidcClient#331]
When run the ConsoleClientWithBrowser project in master branch, throw an exception here.

![图片](https://user-images.githubusercontent.com/1249955/127128520-35762c18-28fd-4646-9cca-94c9df00995e.png)

**Comment by leastprivilege** [comment]
OK - that's a bummer. I am gone for holidays now. Feel free to research why this doesn't work anymore yourself...

**Comment by corneliusmunz** [comment]
@leastprivilege I have the same issue and found the following fix: https://github.com/dotnet/aspnetcore/issues/28112
