### ISSUE TITLE
Elevation of privilege

### ISSUE THREAD

**Issue by Oberndorfer** [DuendeArchive/IdentityModel.OidcClient#332]
Hi,
How can I implement or deal with an operation that requires an elevation of privilege?
I don't want to login another user. I want to keep the access token of the originally logged in user valid. Just for a single operation.
I did more or less use your WinForms WebView example - the browser is in process in a Windows.Forms.Form (not system browser).
Do you  have any ideas or hints?

**Comment by leastprivilege** [comment]
No - that's beyond the scope of this library.
