### ISSUE TITLE
Android 2FA issue in OIDC - Page dissapears when user navigates to see the OTP & come back to the App

### ISSUE THREAD

**Issue by ananthasivanvk** [DuendeArchive/IdentityModel.OidcClient#333]
This is happening with Android where user is shown the OIDC Login Page and when the Multi Factor Authentication  is enabled and when the Android browser prompts for the code and user navigates to see their OTP in email and when they come back to the app the web page is no more their in the app. This happens in Android.

I am using IdentityModel.OidcClient v3.1.2.

<img width="835" alt="Screenshot 2021-08-03 at 6 34 33 PM" src="https://user-images.githubusercontent.com/3005400/128020663-e8856097-5d23-406e-8d69-712355218219.png">

**Comment by Djeffl** [comment]
I'm experiencing the same issue, I can't seem to find a work-around for this issue.... Any solution yet?

**Comment by ananthasivanvk** [comment]
> I'm experiencing the same issue, I can't seem to find a work-around for this issue.... Any solution yet?

We could resolve this by using WebAuthenticator, you may refer the below link for how this can be done, [Xamarin OIDC](https://mallibone.com/post/xamarin-oidc)
