### ISSUE TITLE
Error loading discovery document: Issuer name is missing in 4.0.0

### ISSUE THREAD

**Issue by gjvdkamp** [DuendeArchive/IdentityModel.OidcClient#334]
Hi, 

We just upgraded from 3.1.2 to 4.0.0 but running into "Error loading discovery document: Issuer name is missing"

```
var options = new OidcClientOptions() {
  Authority = Repo.Authority, // "https://xlconnect-oidc.azurewebsites.net"
  ClientId = <<redacted>>
  Scope = "openid profile offline_access xlc.api",
  RedirectUri = redirectUri
};

var client = new OidcClient(options);
var loginState = client.PrepareLoginAsync().Result;
```

The [discovery doc](https://xlconnect-oidc.azurewebsites.net/.well-known/openid-configuration) does show the issue name: 

```
{
"issuer": "https://xlconnect-oidc.azurewebsites.net",
"jwks_uri": "https://xlconnect-oidc.azurewebsites.net/.well-known/openid-configuration/jwks",
"authorization_endpoint": "https://xlconnect-oidc.azurewebsites.net/connect/authorize",
```
and the issuer matches (although that is a different error): `CN = *.azurewebsites.net`

I also tried disabling the check:

```
var options = new OidcClientOptions() {
  Authority = Repo.Authority, 
  ClientId = "xlc.addin",
  Scope = "openid profile offline_access xlc.api",
  RedirectUri = redirectUri,                
  Policy = new Policy { 
    Discovery = new IdentityModel.Client.DiscoveryPolicy {   
      ValidateIssuerName = false // TODO TEMP SECURITY RISK!!  
    }  
  }
};
```
but that threw this error: 
`InvalidOperationException: Error loading discovery document: Error connecting to https://xlconnect-oidc.azurewebsites.net/.well-known/openid-configuration. Operation is not valid due to the current state of the object..`

Any tips where I should be looking next?

**Comment by 64Soft** [comment]
Same for me. I was using Auth0.OidcClient.WinForms v3.2.1 which used IdentityModel.OidcClient 3.1.2.
But the latest version Auth0.OidcClient.WinForms v3.2.3 now uses IdentityModel.OidcClient 4.0.0 and I now also get the same error as the OP when I run my app after this upgrade.

**Comment by leastprivilege** [comment]
I saw a similar problem somewhere else (but can't find it right now). 

IIRC it was related to a problem in the .NET Core JSON APIs - can you try upgrading to the lastest System.Text.Json?

**Comment by 64Soft** [comment]
On my side it's a .NET Framework 4.7.2 winforms app and using Newtonsoft as
Json serializer...

Op do 26 aug. 2021 15:34 schreef Dominick Baier ***@***.***>:

**Comment by leastprivilege** [comment]
4.0 is not using Newtonsoft anymore.

**Comment by gjvdkamp** [comment]
Ok that seems to be the cause indeed, we're also on .Net Framework. Don't have time to check now, will get back when we can try this again.

**Comment by mallibone** [comment]
Thanks for the tip with the NuGet @leastprivilege - that was what was causing my XF client implementation to fail. After upgrading to the latest version (6.*), it automagically started working again.
