### ISSUE TITLE
Error loading discovery document when trying to connect to Cognito 

### ISSUE THREAD

**Issue by A1exandre** [DuendeArchive/IdentityModel.OidcClient#335]
Hi,

I have a windows client that I am trying to get to login on a AWS Cognito user pool.
Given my windows client cannot really open a webview, I'm using the exemple from ConsoleClient (i.e. open a system browser, which redirects to localhost). 

When I try the code below, I get the following error:

> System.InvalidOperationException: 'Error loading discovery document: Error connecting to https://XXXX.auth.us-east-2.amazoncognito.com/.well-known/openid-configuration: Bad Request'  Inner Exception: JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.

Cannot  seem to find any way to resolve this issue.  Any idea what the root cause could be?

```

`
 static string _authority = "https://XXXXXauth.us-east-2.amazoncognito.com";
        static string _api = "https://XXXXXauth.us-east-2.amazoncognito.com/login";
        static OidcClient _oidcClient;
        static HttpClient _apiClient = new HttpClient { BaseAddress = new Uri(_api) };

```
        private async void ButtonClick(object sender, RibbonControlEventArgs e)
        {
            var browser = new SystemBrowser();
            string redirectUri = string.Format($"http://127.0.0.1:{browser.Port}");

            var options = new OidcClientOptions
            {
                Authority = _authority,
                ClientId = "XXXXXXXXX",
                RedirectUri = redirectUri,
                Scope = "email",
                Browser = browser,

               RefreshTokenInnerHttpHandler = new HttpClientHandler()
            };

         
            _oidcClient = new OidcClient(options);
            var result = await _oidcClient.LoginAsync(new LoginRequest());

            _apiClient = new HttpClient(result.RefreshTokenHandler)
            {
                BaseAddress = new Uri(_api)
            };

            `

**Comment by leastprivilege** [comment]
> JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.

Sounds like it is not well-formed JSON - have you checked the document manually?

**Comment by A1exandre** [comment]
Well, because I'm using Cognito, and given it's AWS, I had the bias it was impossible for them not to implement OpenID properly... so I didn't check and assume the problem was elsewhere.

Now that I'm checking - it turns out AWS Cognito fails to implement ".well-known/openid-configuration" properly if you use a custom domain. 

Leaving the details below if other people are trying to work with AWS Cognito. Will update if I find a solution. 

Meanwhile, is it possible to deactivate the client checking ".well-known/openid-configuration" or is it required? Or to set the openid-configuration to a different URL?

-----

e.g. point your browser to the URL without custom domain and you get a properly defined openid config JSON.

https://cognito-idp.{your region}.amazonaws.com/{your pool ID}/.well-known/openid-configuration

Now, if you use a custom domain try pointing your browser to the URL below, and you will see there is nothing but an error message:

https://{your poolname's cusotm domain}.auth.us-east-2.amazoncognito.com/.well-known/openid-configuration

**Comment by leastprivilege** [comment]
I think you can set all parameters manually...it's been a while, you would need to check the source code..

**Comment by A1exandre** [comment]
OK, so solution for using with Cognito with custom domains:

1) set api endpoint on custom domain, and discovery location NOT on custom domain
```
static string _authority = "https://cognito-idp.us-east-2.amazonaws.com/us-east-2_QC23oNrd7/";
static string _api = "https://plzfix.auth.us-east-2.amazoncognito.com/login";

```
2) De-activate those two options so that endpoint on different domain than authority doesn't block the client
options.Policy.Discovery.ValidateEndpoints = false;
options.Policy.Discovery.ValidateIssuerName = false;

**Comment by A1exandre** [comment]
OK, so solution for using with Cognito with custom domains:

1) set api discovery location NOT on custom domain
```
var options = new OidcClientOptions
            {
                Authority = "https://cognito-idp.us-east-2.amazonaws.com/us-east-XXXXXX",
.....
```
2) De-activate those two options so that endpoint on different domain than authority doesn't block the client
options.Policy.Discovery.ValidateEndpoints = false;
options.Policy.Discovery.ValidateIssuerName = false;
