### ISSUE TITLE
Is this similar to ComponentPro.Saml dll ?

### ISSUE THREAD

**Issue by amitt0488** [DuendeArchive/IdentityModel.OidcClient#34]
Is this library similar to ComponentPro.Saml dll ?
I need to replace Shibboleth implementation (SAML) with OpenIdconnect in one of my project.
Is there some class like AuthnRequest which could perform redirection and validation for me?

**Comment by leastprivilege** [comment]
This is for native client apps. If you are looking for a .net lib for server apps, check out Microsoft Katana or ASP.NET Core.
