### ISSUE TITLE
LoginResult property AccessTokenExpiration DateTime.Now

### ISSUE THREAD

**Issue by initialspark** [DuendeArchive/IdentityModel.OidcClient#37]
Hello,

I was wondering why for the LoginResult in the oidc client the AccessTokenExpiration uses DateTime.Now instead of DateTime.UtcNow? And i guess the same applies to AuthenticationTime.

```
var loginResult = new LoginResult
            {
                Claims = FilterClaims(result.Claims),
                AccessToken = result.TokenResponse.AccessToken,
                RefreshToken = result.TokenResponse.RefreshToken,
                AccessTokenExpiration = DateTime.Now.AddSeconds(result.TokenResponse.ExpiresIn),
                IdentityToken = result.TokenResponse.IdentityToken,
                AuthenticationTime = DateTime.Now
            };`
```
Thanks,

Sandeep

**Comment by leastprivilege** [comment]
tbh - I can't remember - maybe because i was thinking "local time" - but maybe `DateTimeOffset` would be better here.

Wanna do some research about what's best - and tell me?

**Comment by leastprivilege** [comment]
Any results?

**Comment by leastprivilege** [comment]
closing - no response.
