### ISSUE TITLE
Where does the "data"-parameter come from that is shown in the readme.md?

### ISSUE THREAD

**Issue by ghost** [DuendeArchive/IdentityModel.OidcClient#4]
Hi, I'm trying to implement the OidcClient2 with a Xamarin Forms app with IdentityServer4 as my identity provider. 

Im getting most of how to implement this with iOS but cannot figure out how where the input paramter 'data' for 'var result = await oidcClient.ProcessResponseAsync(data, state);' comes from? 

Any hints/suggestions? I'm using the SFSafariViewController as my browser.

Thanks!

**Comment by leastprivilege** [comment]
see here

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/iOSClient

**Comment by ghost** [comment]
Thanks alot! Made my day.
