### ISSUE TITLE
Is this library compatible with IdentityServer4

### ISSUE THREAD

**Issue by noufionline** [DuendeArchive/IdentityModel.OidcClient#40]
Hi There,

Since ResourceOwnerPassword is deprecated and ClientCredentials are not a recommended way for native WPF Applications I wanted to use this library to talk to IdentityServer4.

Will ResourceOwnerPassword grant will be removed in future versions of IdentityServer?

Is this library at the moment can be used with IdentityServer4?

If yes, then how can I allow other users to log in to the same app by effectively logging out? at the moment when I try to open the browser again, it's directly taking to concent screen.

Please help me.

**Comment by leastprivilege** [comment]
This library is compatible with IS4.

Logout is a separate issue.
