### ISSUE TITLE
Optional identity tokens

### ISSUE THREAD

**Issue by ljvanschie** [DuendeArchive/IdentityModel.OidcClient#41]
It seems that currently, the OidcClient always requires the token response to include an identity token. When logging in using the authorization code flow, `ProcessCodeFlowResponseAsync()` will call `ValidateTokenResponseAsync()` with the default true value for `requireIdentityToken`.

This means you can't use OidcClient for just acquiring access tokens from an authorization server that does not provide id tokens. Is that right or am I missing a setting?

**Comment by leastprivilege** [comment]
you know what OIDC stands for?

**Comment by ljvanschie** [comment]
I do, I just thought this library could also support a basic OAuth2 flow without requiring identity tokens, as the readme states it is an 'an implemenation of the OIDC/_OAuth 2_ for native apps specification'.

Anyway, from your response I understand that this is not the case :)
I'll see if I can find another OAuth2 library.

**Comment by leastprivilege** [comment]
Yes id_token is required.

**Comment by Renkas** [comment]
Why is it required with `OidcClientOptions.AuthenticationFlow.AuthorizationCode`?

Using this flow the client is not even asking server for id_token and then of course response does not include it and the validation mentioned above fails.

This makes using this library impossible for me also. Please fix this
