### ISSUE TITLE
Install on Profile 44 or 111

### ISSUE THREAD

**Issue by ruisilva450** [DuendeArchive/IdentityModel.OidcClient#42]
Hi, I'm trying to install this via nuget on a PCL with profile 44. Previous to this I tried on profile 111 and still the same result.
Can someone clarify this? 
In the end this is a Xamarin Forms app.
I have other libraries that are .NetStandard (ex. Xam.Settings plugin by @jamesmontemagno James Montemagno) and are running great.

Error:
```Could not install package 'IdentityModel.OidcClient 2.3.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.6,Profile=Profile44', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.```

**Comment by leastprivilege** [comment]
We are targeting

    <TargetFrameworks>net452;netstandard1.4;netstandard2.0</TargetFrameworks>

Not sure if this includes your target. See here:

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by leastprivilege** [comment]
Any update?

**Comment by ruisilva450** [comment]
It doesn't support the profiles I try to target because profile 44 has netstandard1.2 and profile 111 has netstandard1.1.
Thanks anyway

**Comment by leastprivilege** [comment]
Yeah - that wouldn't work because the necessary crypto libs are missing.
