### ISSUE TITLE
How to transform GetUserInfoAsync to ClaimsPrincipal

### ISSUE THREAD

**Issue by filoe** [DuendeArchive/IdentityModel.OidcClient#45]
I'm getting a ClaimsPrincipal instance from the `LoginAsync` method.
My identity server is using refresh tokens. So I am refreshing the access token and also would like to get updated claim values. My application uses the `ClaimsPrincipal` object. I was wondering, how can I retrieve claims using `GetUserInfoAsync` and transform them to `ClaimsPrincipal` like `LoginAsync` does.

Also the `LoginResult` provides a `RefreshTokenHandler`.
How can I construct a `RefreshTokenHandler` when using `RefreshTokenAsync`?

**Comment by leastprivilege** [comment]
I assume this is solved by now..?!
