### ISSUE TITLE
Error loading discovery document: Issuer name does not match authority

### ISSUE THREAD

**Issue by filoe** [DuendeArchive/IdentityModel.OidcClient#46]
IdentityServer4 allows you to overwrite the IssuerUri. 
I'm using this in dev environment because my identityserver gets calles from localhost (some microservice running on localhost on some other ports) AND from other hosts (e.g. any mobile devices).
On these mobile devices, IdentityModel.OidcClient2 is running which access the identityserver through it's ip (let's say 192.168.1.1).
The problem is that other microservices which rely on the token issued by identityserver are probing the issuer. Clients running on localhost (for example a browser which accesses identityserver and microservice) will have tokens issued by http://localhost:5000. And the mobile device would use a token issued by http://192.168.1.1:5000. 
In the microservice I have to set ONE issuer (let's say http://localhost:5000). 
In order to allow a mobile device (using this library) access the microservice, I have to use always the same issuer on identityserver which is different than the authority. 

See also: https://github.com/IdentityServer/IdentityServer4/issues/1207.

Can we remove that check?

**Comment by leastprivilege** [comment]
You can disable the check on the discovery policy.

**Comment by leastprivilege** [comment]
That being said - the spec demands that the issuer is set to the base address of the server - IOW you should get your DNS right.

**Comment by filoe** [comment]
Thanks! I will only use this in dev scenario. I don't have a local dns.

**Comment by estebanl** [comment]
How can disable the check on the discovery policy ?

**Comment by fgauna12** [comment]
```
var discoveryClient = new DiscoveryClient(yourAuthority);
discoveryClient = new DiscoveryPolicy {ValidateIssuerName = false};
```

**Comment by HelloMyDevWorld** [comment]
int var options = new  OidcClientOptions ();

 options.Policy.Discovery.ValidateIssuerName = false;
