### ISSUE TITLE
Authenticating client with client-assertion (jwt)

### ISSUE THREAD

**Issue by steinarnoem** [DuendeArchive/IdentityModel.OidcClient#48]
Hi, I know this isn't an issue, but a question.. :) But, hopefully you can give me some pointers..

We would like to try out client authentication in a WPF application using the OidcClient by passing client-assertions (jwt's).

Would adding the neccessary params by passing extra parameters in the PrepareLoginAsync() method be the way to go?

**Comment by leastprivilege** [comment]
Hey, 

the client assertion would be used on the back-channel - not the front-channel. So if you use the prepare/process approach - the process response method has extra parameters too IIRC 

let me know if this makes sense

**Comment by steinarnoem** [comment]
Thanks for the quick feedback!
It makes sense 👍 

I'll give it a try :)

**Comment by steinarnoem** [comment]
Oh, I'm such a lazy bastard.. You've got examples in your tests :)

https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/dev/test/IdentityModel.OidcClient.Tests/HybridFlowResponseTests.cs

Thank you!

**Comment by leastprivilege** [comment]
I think you are confused now ;)

I am thinking of this 

https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/dev/src/IdentityModel.OidcClient/OidcClient.cs#L145

**Comment by steinarnoem** [comment]
Haha, lazy and confused - special mix.

I thought https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/dev/test/IdentityModel.OidcClient.Tests/HybridFlowResponseTests.cs#L89 gave an example of usage..
 
But, then set the assertion, and assertion_type params instead of the id_token..
