### ISSUE TITLE
Question to confirm I'm using the preferred desktop login option

### ISSUE THREAD

**Issue by gary-archer** [DuendeArchive/IdentityModel.OidcClient#50]
Nice library guys - my company provides some desktop apps for investment banks. I was hoping you could confirm that I am following the recommended direction below.

**LOGINS SHOULD NOT USE WEB VIEWS**
This seemed to be the standard technique a few years ago, using callback URLs such as *urn:ietf:wg:oauth:2.0:oob*, but this is no longer considered to be good security. Also, Single Sign On and Password Autofill won't work on a web view.

**LOGINS SHOULD USE THE SYSTEM BROWSER**
This [Auth0 Link](https://auth0.com/blog/oauth-2-best-practices-for-native-apps/) summarizes the issue - logins must use the desktop browser to be considered good security.

**OPTIONS**
The [OAuth Standards for Native Apps](https://tools.ietf.org/search/rfc8252) mentions 3 redirect options:
* Private URI Scheme
* Claimed HTTPS Scheme
* Loopback Interface

**OPTION 1 - Private URI Scheme (com.mycompany.com:/mydesktopapp)**

* Works for Mobile apps
* Works for desktop apps with special OS support, such as Windows Universal apps

I could not use this scheme for my WPF app - the System browser will refuse to redirect to a URL of this form.

**OPTION 2 - Claimed HTTPS Scheme (https:/mycompany.com/myapp)**

I think this also requires special operating system support - I cannot use it for my WPF app.

**OPTION 3 - Loopback Interface (http://127.0.0.1:8000)**
This seems to be the recommended option:

* The end user PC needs to run a simple (low privilege) web server
* It works for a Desktop App, without special OS support

It looks like the only good option for desktop logins.

**PLANNING DEPLOYMENT**
We need to tell IT staff at investment banks to not block the local web server.
If we ever ran into an IT department who refused to allow it, the only backup option we could offer would be to login on a web view.

**Comment by leastprivilege** [comment]
looks right to me. Private URI schemes work as well for Windows/Mac desktop. You can have a look at GitHub Desktop for an example of the UX.

**Comment by gary-archer** [comment]
Thanks for that Dominick - good answer - though there are still some challenges here.

**RELIABLE + POLISHED DESKTOP LOGIN USER EXPERIENCE**
These aspects are not really covered in any online sample or article - Login UX is something that business owners at my company (and many others) will care a a lot about.

**ALLOWING THE USER TO RETRY**
This is awkward at best to implement using the loopback interface:

* The user may click Sign In in the Desktop App then accidentally close the browser tab
* The Desktop UI needs to keep a Sign In button available in order to allow the user to retry
* But you only want to start one loopback listener if the user clicks Sign In twice
* And you want to clean up listener resources reliably once the user is logged in
* The desktop app gets no notification if the user closes the browser tab
* We'd like to avoid relying on our customer IT policy allowing the loopback listener

**[GITHUB DESKTOP](https://desktop.github.com/)** 
* On my Windows PC this registers a custom URI scheme (x-github-client) as described in [This Microsoft Article](https://msdn.microsoft.com/en-us/library/aa767914(v=vs.85).aspx)  (I wasn't aware you could do that)
* The browser does a login for the desktop client without PKCE handling
* The browser posts the authorization code to GitHub Desktop via the custom URI scheme
* GitHub Desktop uses a fixed client secret to swap the code for tokens

**BROWSER PAGE AFTER LOGIN**
* Some companies will care about what is shown here
* GitHub Desktop shows a blank page
* Instagram has a Desktop App and after login the browser is left logged into the Instagram web site
* Redirecting to the company home page is one option?

**I'M LEANING TOWARDS CUSTOM URL SCHEMES**
* Just needs some simple installer work to register the scheme
* No risk of listeners being blocked by IT departments once deployed
* I want to use PKCE handling so that the security is right
* May be simpler to code reliably using URL schemes rather than listeners
* I've still not seen any real world apps that use the loopback interface

As always, coding is the easy part - getting past blocking issues is what concerns me. I will post back once I feel we've got things as good as we can - hopefully the lessons learned will be useful to others also.

**Comment by leastprivilege** [comment]
We've added a sample using custom URL scheme on Windows

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/WindowsConsoleSystemBrowser
