### ISSUE TITLE
What about Unity ?

### ISSUE THREAD

**Issue by Vinnythetrue** [DuendeArchive/IdentityModel.OidcClient#52]
Is this client implementation usable with Unity ? Did someone already achieve it successfuly ?

Thanks for your time,
Vinny

**Comment by leastprivilege** [comment]
I never tried it...

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by peterhorsley** [comment]
Sorry to comment on this closed issue, just wanted to mention I just got this library working in Unity 2018.1 today, so far on Android, using an implementation of IBrowser based on the CustomTabs class found here: https://qiita.com/lucifuges/items/b17d602417a9a249689f (you'll need to google translate from Japanese to English).  I also needed to add the certificate validation code from here: https://stackoverflow.com/a/33391290/325442.  I used UnitySendMessage to pass the received authorization code response from a native android plugin back to the c# code.

**Comment by styk-tv** [comment]
@peterhorsley i have spent several days trying 2018.2 with your example https://github.com/peterhorsley/Unity3D.Authentication.Example and no luck, probably went over your steps 50 times and have read the Japanese page another 50. Anything lost in translation.....? I'm dehydrated, my left eye is twitching and I'm ready to have a nervous breakdown, somewhere in the desperation of it all I tried to send you $250 on twitter (or might have been Dominick @leastprivilege). But not enough zeros i guess. (anyone wants this bounty, email me to confirm)

**Comment by peterhorsley** [comment]
hi Peter, yeah I know how you feel, dealing with authentication is
horrible. I'm pretty sure I have it working on ios and Android on 2018.2. I
will check today and get back.

**Comment by peterhorsley** [comment]
Confirming that example is working with Unity 2018.2.0.30296.
