### ISSUE TITLE
at_hash is missing

### ISSUE THREAD

**Issue by jachin84** [DuendeArchive/IdentityModel.OidcClient#55]
I just tried the built in ConsoleClient using Azure Active Directory.  I received an error stating that the at_hash is missing. 

Digging into this a bit it looks like the issue is at https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/f8fc3501aea43c16f1ada2d0dcf429464dd3015e/src/IdentityModel.OidcClient/ResponseProcessor.cs#L210.

By default the Policy has RequireAccessTokenHash = True. In the case of a hybrid flow ("code id_token") it looks like it's optional to include the at_hash. See http://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken. Ie. After validating the id_token from the front-channel and then redeeming the authorization code there is no requirement for the token endpoint to give a at_hash.

I'm wondering if it would be a better default to have RequireAccessTokenHash = false when using a Hybrid Flow?

**Comment by leastprivilege** [comment]
Since this library really only supports hybrid and code flow - this could be disable by default. 

Was it hard to find the problem?

**Comment by jachin84** [comment]
The at_hash may be present during a code flow although the client is not required to validate it. See [here](http://openid.net/specs/openid-connect-core-1_0.html#CodeFlowTokenValidation). Maybe in this case the logic could simply be to validate the at_hash if it is present?

Re: finding the problem. It was reasonably easy to locate the issue but it did take time to understand why the at_hash might be missing. Ie. had to go read the spec.

**Comment by leastprivilege** [comment]
>  had to go read the spec.

That's a good thing ;)

**Comment by leastprivilege** [comment]
I will leave this open - I don't have the time right now to think about the possible implications.

**Comment by leastprivilege** [comment]
Will consider for v3

**Comment by leastprivilege** [comment]
OK. I changed the default to false.
