### ISSUE TITLE
LogoutAsync - API call doesn't work explicitly,  throws exception due to lack of ProviderInformation.

### ISSUE THREAD

**Issue by anvaraj78** [DuendeArchive/IdentityModel.OidcClient#57]
LogoutAsync API call doesn't work explicitly as it does't have provider Information internally and throws exception.  I think unlike LoginAsync or GetUserInfoAsync API, logout doesn't have discovery document fetch call internally.
I have a requirement to call the logoutAsync APIs from a client application where it already has a valid token/successful authentication and user has relaunched/restarted the application and trying to invoke the logout.

Just instantiating the OidcClient object and calling LogoutAsync, doesn't work.

**Comment by leastprivilege** [comment]
OK - good point - do you want to fix that via a PR -- for both LogoutAsync and PrepareLogout.

**Comment by leastprivilege** [comment]
nevermind - working on it..

**Comment by leastprivilege** [comment]
nuget pushed. thanks for reporting.
