### ISSUE TITLE
Create oidc console client without web server

### ISSUE THREAD

**Issue by xaviergxf** [DuendeArchive/IdentityModel.OidcClient#59]
Hi,

  I was looking into the console clients and wondering if there's a way to do the same login procedure without using a weblistener or kestrel, only using httpclient. Is this possible?  It would be great to remove a dependency like a webserver for a simple console app.

Thanks

**Comment by leastprivilege** [comment]
Have a look here

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/WindowsConsoleSystemBrowser
