### ISSUE TITLE
RedirectUris trailling slash

### ISSUE THREAD

**Issue by dpedrelli** [DuendeArchive/IdentityModel.OidcClient#6]
If the redirect Uris, between IdentityServer and IdentityModel.OidcClient2, don't match exactly, including whether there is trailing slash, the log produces an error of an invalid redirect Uri.  The IdentityServer console does not report anything.  This is only apparent, if you enable logging within IdentityServer.  It is not difficult to make sure that the Uris between the client and the server are exact.  However, it seems like the comparison should not fail based on the difference of a trailing slash.

**Comment by leastprivilege** [comment]
The spec says that the redirect Uri must be an exact match.


-------
Dominick Baier
