### ISSUE TITLE
Using backwards compatible iOS SafariViewController for Xamarin.Forms

### ISSUE THREAD

**Issue by ryanmendoza** [DuendeArchive/IdentityModel.OidcClient#60]
I have looked at the Xamarin.Forms sample and it seems unclear to me how I would use (or reference) the iOSClient implementation of `SFSafariViewController` instead of `SFAuthenticationSession` with the `IBrowser` interface. Is it possible to accomplish this with OidcClient2?

**Comment by leastprivilege** [comment]
The samples repo has both versions.

**Comment by mleech** [comment]
Here's a (fairly hacky) sample implementation of a pre-iOS 11 `IBrowser` implementation
```csharp
public class SafariBrowser : IBrowser
{
    public Task<BrowserResult> InvokeAsync(BrowserOptions options)
    {
        var task = new TaskCompletionSource<BrowserResult>();

        var safari = new SFSafariViewController (new NSUrl (options.StartUrl));

        AppDelegate.CallbackHandler = async url =>
        {
            await safari.DismissViewControllerAsync (true);
            task.SetResult(new BrowserResult()
            {
                Response = url
            });
        };

        // https://forums.xamarin.com/discussion/24689/how-to-acces-the-current-view-uiviewcontroller-from-an-external-service
        var window= UIApplication.SharedApplication.KeyWindow;
        var vc = window.RootViewController;
        while (vc.PresentedViewController != null)
        {
            vc = vc.PresentedViewController;
        }
        vc.PresentViewController (safari, true, null);

        return task.Task;
    }
}
```
see https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/master/iOSClient/iOSClient/AppDelegate.cs for the implementation and usage of the `CallbackHandler` property

**Comment by rinkeb** [comment]
You could also look at https://github.com/auth0/auth0-oidc-client-net/tree/master/src/Auth0.OidcClient.Xamarin.iOS.

**Comment by ryanmendoza** [comment]
@rintje that was exactly what I was looking for. Thanks!

**Comment by ryanbuening** [comment]
FYI - rinkeb's link is dead and the auth0 samples can now be found here: https://github.com/auth0/auth0-oidc-client-net/tree/master/src/Auth0.OidcClient.iOS

I'm also trying to implement SFSafariViewController in my Xamarin Forms app and I'm using the auth0 examples. I'm getting logged in successfully, but getting stopped at "You are now being returned to the application. Once complete, you may close this tab"

Has anyone been able to implement SFSafariViewController successfully and have an example? I'm not seeing any samples of SFSafariViewController that implements IBrowser in the IdentityModel.OidcClient.Samples repo.
