### ISSUE TITLE
Authorize with multiple authorization servers, accessing seperated resources?

### ISSUE THREAD

**Issue by TomRi7755** [DuendeArchive/IdentityModel.OidcClient#62]
Hello,

I would like to know, if I can use this System (OidcClient2) this way:

Authenticate, getting an ID-Token (or do I not need to care about these?).
Afterwards, can I authorize with my authenticated client at multiple different authorization servers to access separated resources?

**Comment by leastprivilege** [comment]
thats not how it works - check the specs please.
