### ISSUE TITLE
Revocation endpoint

### ISSUE THREAD

**Issue by DevInstinct** [DuendeArchive/IdentityModel.OidcClient#63]
It would be useful to have a RevokeAsync() method to support the revocation_endpoint when the authorization_endpoint (LogoutAsync) is not supported.

An example of this is Google, which has no authorization_endpoint, but has a revocation_endpoint.

**Comment by leastprivilege** [comment]
Agreed. Feel free to add it.

**Comment by leastprivilege** [comment]
Is a PR coming? I want to release a new version soon.

**Comment by DevInstinct** [comment]
Not at this time - this isn't a mandatory feature for us, maybe later. Thanks.
