### ISSUE TITLE
ConfigureAwait(false) in the EnsureProviderInformationAsync blocks execution 

### ISSUE THREAD

**Issue by cookie84sa** [DuendeArchive/IdentityModel.OidcClient#64]
After the EnsureProviderInformationAsync method call in the for example method EnsureConfigurationAsync the execution will not continue further. If the  ConfigureAwait(false) is added to calls of  EnsureProviderInformationAsync and EnsureConfigurationAsync everything works fine.

**Comment by leastprivilege** [comment]
Hm - I never ran into this problem..can you elaborate?

**Comment by leastprivilege** [comment]
Any update?

**Comment by PatrickDelancy** [comment]
I encountered this problem in an ASP.NET MVC application, when my controller action wasn't marked async:

```C#
    public class MyController : Controller {
        public ActionResult ProcessResponse() { }
    }
```

Once I made the controller action async, it no longer stopped execution, and I didn't have to try and force synchronous execution to get around it.

```C#
    public class MyController : Controller {
        public async Task<ActionResult> ProcessResponse() { }
    }
```
