### ISSUE TITLE
Configuration for the OpenId Connect of oneLogin.com

### ISSUE THREAD

**Issue by luis-fernando-camacho-dev-projects** [DuendeArchive/IdentityModel.OidcClient#65]
Hi All,

How can I configure this library to use with OpenId Connect of onelogin.com?
Can you help me with that,please?
I tried to configure but all the time I see the final url is:
disco.Error = "Error connecting to https://custom.onelogin.com/oidc/auth/.well-known/openid-configuration: Not Found" but the url should be "https://custom.onelogin.com/oidc/auth"

please see the configuration values necessary for the OpenId Connect with onelogin.com
https://github.com/onelogin/openid-connect-dotnet-core-sample/blob/master/Controllers/AccountController.cs

Thanks,
Luis Camacho

**Comment by brockallen** [comment]
It looks like this is the URL: https://custom.onelogin.com/oidc/.well-known/openid-configuration

**Comment by luis-fernando-camacho-dev-projects** [comment]
Hi Brockallen,
 @brockallen 
thanks for answering.

I fix that error above but  now I get the following error:
[16:05:20 Error] IdentityModel.OidcClient.OidcClient
Error validating token response: Error validating identity token: Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10500: Signature validation failed. No security keys were provided to validate the signature.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at IdentityModel.OidcClient.IdentityTokenValidator.ValidateSignature(String identityToken, JwtSecurityTokenHandler handler, TokenValidationParameters parameters)
   at IdentityModel.OidcClient.IdentityTokenValidator.<ValidateAsync>d__4.MoveNext()

my configuration is the following:


            // create a redirect URI using an available port on the loopback address.
            string redirectUri = string.Format("http://localhost:57021/Home/Index");

            // create an HttpListener to listen for requests on that redirect URI.
            var settings = new WebListenerSettings();
            settings.UrlPrefixes.Add(redirectUri);
            var http = new WebListener(settings);

            http.Start();
            Console.WriteLine("Listening..");

            JsonWebKey keye = new IdentityModel.Jwk.JsonWebKey();
            keye.Kty = "RSA";
            keye.Use = "none";
           
            var set = new IdentityModel.Jwk.JsonWebKeySet();
            set.Keys.Add(keye);



            var options = new OidcClientOptions
            {
                TokenClientAuthenticationStyle = IdentityModel.Client.AuthenticationStyle.PostValues,
                Authority = _authority,
                ClientId = "xxxxxx",
                ResponseMode = OidcClientOptions.AuthorizeResponseMode.FormPost,
                RedirectUri = "http://localhost:57021/Home/Index",
                Scope = "openid profile api",
                FilterClaims = true,
                LoadProfile = true,
                Flow = OidcClientOptions.AuthenticationFlow.AuthorizationCode,
                ClientSecret = "xxxx",

                ProviderInformation = new ProviderInformation()
                {
                    IssuerName = "https://custom.onelogin.com",
                    AuthorizeEndpoint = "https://custom.onelogin.com/oidc/auth",
                    TokenEndpoint = "https://custom.onelogin.com/oidc/token",
                    UserInfoEndpoint =
                    "https://custom.onelogin.com/oidc/me",
                    EndSessionEndpoint = "https://custom.onelogin.com/oidc/token/introspection",
                    KeySet = new JsonWebKeySet()
                }
            };
            options.Policy.Discovery.ValidateIssuerName = false;
            options.Policy.Discovery.ValidateEndpoints = false;
            options.Policy.ValidSignatureAlgorithms = new[] { OidcConstants.Algorithms.Asymmetric.RS256 };
           
           
           

            var serilog = new LoggerConfiguration()
                .MinimumLevel.Verbose()
                .Enrich.FromLogContext()
                .WriteTo.LiterateConsole(outputTemplate: "[{Timestamp:HH:mm:ss} {Level}] {SourceContext}{NewLine}{Message}{NewLine}{Exception}{NewLine}")
                .CreateLogger();

            options.LoggerFactory.AddSerilog(serilog);

            var client = new OidcClient(options);
            client.Options.ResponseMode = OidcClientOptions.AuthorizeResponseMode.FormPost;
            var state = await client.PrepareLoginAsync();
            OpenBrowser(state.StartUrl);
            var context = await http.AcceptAsync();
            var formData = GetRequestPostData(context.Request);

            if (formData == null)
            {
                Console.WriteLine("Invalid response");
                return;
            }
            var result = await client.ProcessResponseAsync(formData, state);
}

How can I fix this issue ? Could you help me with that please?

**Comment by leastprivilege** [comment]
Any update?

**Comment by PatrickDelancy** [comment]
I believe this may be related to pull request #77 that I just submitted.

If you look at the jwk ( https://custom.onelogin.com/oidc/certs ) , you will notice that the "use" member is missing. The error message you mentioned is the same error message I was receiving.

**Comment by leastprivilege** [comment]
that change was released. Give it a go and tell us if it worked. Closing for now.
