### ISSUE TITLE
Error loading discovery document: "Http" - "Error connecting to https://api.xyz.com/.well-known/openid-configuration: Not Found"

### ISSUE THREAD

**Issue by wjvii** [DuendeArchive/IdentityModel.OidcClient#66]
The API I am calling using OAuth 2.0 does not have this document and I am wondering if there is a way to make it bypass checking for this document and what needs to be supplied that it might have retrieved from the document if not found.

I have tried various items that seemed to make sense to me such as options.RefreshDiscoveryDocumentForLogin = false; but that didn't help.

Thank you in advance for any assistance.

**Comment by leastprivilege** [comment]
> The API I am calling using OAuth 2.0 does not have this document

Then you are using the wrong library. As the name implies this is about OpenID Connect.

Try the plain IdentityModel library which has support for the OAuth primitives.

https://github.com/IdentityModel/IdentityModel2

**Comment by wjvii** [comment]
Thank you so much for the information, I will give the other library a try. I had read this "OidcClient is an implementation of the OIDC/OAuth 2 for native apps specification for C#." in the description and thought it applied to OAuth 2.0 as well. From my additional reading I see that the two, OIDC and OAuth 2.0, are related and understand the description better.
