### ISSUE TITLE
Calling RefreshTokenAsyncthrows exception

### ISSUE THREAD

**Issue by jerriep** [DuendeArchive/IdentityModel.OidcClient#7]
How is the `RefreshTokenAsync` method supposed to be used? 

When I instantiate a new instance of `OidcClient` and call the `RefreshTokenAsync` method with a previously saved `refresh_token`, I get a `NullReferenceException` with the following stack trace relevant to OidcClient

```
at IdentityModel.OidcClient.Infrastructure.TokenClientFactory.Create(OidcClientOptions options)
at IdentityModel.OidcClient.OidcClient.<RefreshTokenAsync>d__12.MoveNext()
```

It would seem that `TokenClientFactory.Create` depends on the `ProviderInformation` being initialized (see https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/dev/src/IdentityModel.OidcClient/Infrastructure/TokenClientFactory.cs#L10-L21).

When I first call `LoginAsync` and then `RefreshTokenAsync`, all works fine, because `EnsureConfigurationAsync` was called in that case (https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/dev/src/IdentityModel.OidcClient/OidcClient.cs#L61), which will load the information from the discovery document.

Am I misunderstanding the use case. Surely I must be able to initialize an instance of `OidcClient` at a later stage and use it to refresh a token which was previously saved when a user authenticated?

**Comment by leastprivilege** [comment]
yes that's a bug. fixing it now.

Another way to use refresh tokens is via the RefreshTokenHandler. Have you tried that?

**Comment by leastprivilege** [comment]
done

**Comment by softsan** [comment]
@leastprivilege  How to use RefreshTokenHandler in xamarin client?
