### ISSUE TITLE
Do you need to increment the version number for NuGet publish?

### ISSUE THREAD

**Issue by jabba2324** [DuendeArchive/IdentityModel.OidcClient#71]
Hi

Looking here: https://www.nuget.org/packages/IdentityModel.OidcClient/

It looks as though none of the changes merged in the last 25 days have been published with their own version number and are probably not available via NuGet. Do you need to update something in AppVeyor or am I just being impatient?

**Comment by leastprivilege** [comment]
next week...

**Comment by jabba2324** [comment]
Ok Thanks

**Comment by leastprivilege** [comment]
done: https://github.com/IdentityModel/IdentityModel.OidcClient2/releases/tag/2.8.0

thanks for helping out!
