### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by rajeshaz09** [DuendeArchive/IdentityModel.OidcClient#78]
I am receiving following error.
**"Error loading discovery document: Endpoint is on a different host than authority: https://jeeveserpcloud.auth.us-east-1.amazoncognito.com/oauth2/authorize"**
My discovery URL is
https://cognito-idp.us-east-1.amazonaws.com/us-east-1_KOnPlnUFl/.well-known/openid-configuration

**Comment by leastprivilege** [comment]
This is not related to CORS - by default we validate that all endpoints are on the same host as the disco endpoint.

You can turn off endpoint validation on the policy.
