### ISSUE TITLE
Use of RefreshTokenHandler when refresh_token grant does not return a new refresh token

### ISSUE THREAD

**Issue by SergioETrillo** [DuendeArchive/IdentityModel.OidcClient#79]
Hi,

I am using the `OidcClient `to obtain a `LoginResult `instance, (after user authentication), then create a `httpClient `using the `result.RefreshTokenHandler`.

Then I make a request to the relevant resource server using that `httpClient`.  It works for the first access token, and when it expires, it gets a new one successfully. But because the identity provider does not return a new refresh token on a refresh_token grant, the Refresh Token property in the handler does not get updated, (changes to null).  Therefore when that new access token expires again, the call managed by the handler to /oauth/token fails due to the lack of Refresh Token.

Is there a way to reuse the first refresh token obtained within the httpclient handle? 

FYI I am using Auth0 and I would swear that they were providing a new refresh token every time there was a refresh token grant until recently, but not anymore. Checking the RFC 6479 the return of a new refresh token is indeed an optional feature.

Any help will be appreciated, apologies if this is the wrong forum.

**Comment by leastprivilege** [comment]
I see - well that needs code changes. Feel free to start a discussion/PR here

https://github.com/IdentityModel/IdentityModel2/issues/135

not sure when I will have the time to do it myself.

**Comment by leastprivilege** [comment]
Will re-design the handler in v3

**Comment by leastprivilege** [comment]
I forgot - this has been fixed.
