### ISSUE TITLE
signout capability in OidcClient

### ISSUE THREAD

**Issue by mothupally** [DuendeArchive/IdentityModel.OidcClient#8]
Hi, I couldn't find a method to signout with in **OidcClient** class. Can you please clarify if the signout url is expected to be built manually and be invoked?

Thanks!

**Comment by leastprivilege** [comment]
It is not implemented yet.

What does signout mean to you in a native app?

**Comment by markirving2** [comment]
I was also wondering why the signout isnt implemented and your question about the meaning of signout for native apps has challenged my mindset. In the situation where I am trying to use identityserver4 with an external AAD, not allowing the native winform app to signout means the cookies remains in the web authentication browser for both ID4 and the external AAD. This means a different person could start the app and be fully logged in via the existing cookies. - or am I thinking all wrong.

**Comment by markirving2** [comment]
or I might be confused with MVC behaviour.. I aint seeing cookies persisting in my winform app currently.

**Comment by leastprivilege** [comment]
Signout means many things to different people - 

* you could delete the cookie in the browser (doesn't seem to be the issue in your case)
* you could trigger a "single sign out" - meaning the user might also get signed out in other applications on different computers (if the idp has a mechanism for that)
* you could simply delete and/or revoke all your active tokens

What do **you** want to achieve?

**Comment by markirving2** [comment]
Signout for me is simply making sure another person cant ride on a previous user's authentication ie cookie deletion. Thank-you for your reply

**Comment by leastprivilege** [comment]
I will add a feature to call the end session endpoint via the same browser implementation. 

 #25
