### ISSUE TITLE
Missing option for BasicAuthenticationHeaderStyle

### ISSUE THREAD

**Issue by e-tobi** [DuendeArchive/IdentityModel.OidcClient#80]
There seems to be no way to use OidcClient with a different BasicAuthenticationHeaderStyle.
I stumbled upon this, because the server requires BasicAuthenticationHeaderStyle.Rfc2617 but BasicAuthenticationHeaderStyle.Rfc6749 is used by default. (Rfc6749 will url-encode client-id and client-secret before bas64-encoding them.)

A new option for this could be added and used in the TokenClientFactory to set the BasicAuthenticationHeaderStyle property of the token client.

**Comment by leastprivilege** [comment]
Why do you need authentication for a public client?

**Comment by leastprivilege** [comment]
So yes - this would be doable.

Which OIDC provider are you using?

**Comment by thoemy** [comment]
The OIDC provider for the DATEVconnect online APIs also require Rfc2617 encoded values. The documentation is not public but here is an excerpt from it

> The client sends the client_id and client_secret, separated by a single colon (":") character, within base64 encoded string in the credentials as HTTP Basic Authentication header (http://tools.ietf.org/html/rfc2617).

DATEV is a big company in Germany that provides financial accounting software and services. It would be nice to have an option to control this.

**Comment by HKiessling** [comment]
Yes, this ist a bug at this Identity-Provider. 
The problem ist, that this bug was not discovered, because the OidcClient had the same bug. 
Ask for a password which is identical which and without Rfc2617 encoding.
In the next weeks will the bug be fixed.

**Comment by thoemy** [comment]
@HKiessling thanks for letting us know that this is going to be fixed. We worked around this by intercepting the HTTP calls with a BackchannelHandler that encodes the Authorization header using Rfc2617.

**Comment by robinvdbroek** [comment]
@thoemy could you share the final solution that you've came up with using the BackchannelHandler? I'm having a same issue with an OpenID Connect server that requires Rfc2617 encoding.

**Comment by thoemy** [comment]
@robinvdbroek this should be the relevant code.

```csharp
internal class AuthFixupBackchannelHandler : HttpClientHandler
{
    private readonly Config _config;

    public AuthFixupBackchannelHandler(Config config)
    {
        _config = config;
    }

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        // https://github.com/IdentityModel/IdentityModel.OidcClient2/issues/80
        if (request.Headers.Authorization != null)
        {
            var bytes = Convert.FromBase64String(request.Headers.Authorization.Parameter);
            var decoded = Encoding.UTF8.GetString(bytes);
            if (decoded.StartsWith(_config.ClientId))
            {
                bytes = Encoding.UTF8.GetBytes($"{_config.ClientId}:{_config.ClientSecret}");
                request.Headers.Authorization = new AuthenticationHeaderValue("Basic", Convert.ToBase64String(bytes));
            }
        }

        return base.SendAsync(request, cancellationToken);
    }
}
```

and

```csharp
var config = new Config() {
	ClientId = "MyClientId",
	ClientSecret = "MySecret",
};

var options = new OidcClientOptions
{
    // Other options
    ClientId = config.ClientId,
    ClientSecret = config.ClientSecret,
    BackchannelHandler = new AuthFixupBackchannelHandler(config),
};

var client = new OidcClient(options);
```
