### ISSUE TITLE
Tested against AWS Cognito?

### ISSUE THREAD

**Issue by jchannon** [DuendeArchive/IdentityModel.OidcClient#81]
I have a local asp.net core application with an api endpoint.  I have a AWS Cognito user pool setup.  I can go through an index.html page and some Javascript to log into Cognito and get a token back. I can then make a request to asp.net core app with the token and after the token validation get to my api endpoint.

Using the sample netcore app for this library I tried hooking it all up but get back an error when it reads the discovery document.

`Endpoint is on a different host than authority: https://REDACTED.auth.eu-west-2.amazoncognito.com/oauth2/authorize`

Looking at the raw json in the discoveryResponse that is correct.

Is there something that can be done to make this work?

```
{
	"authorization_endpoint": "https://REDACTED.auth.eu-west-2.amazoncognito.com/oauth2/authorize",
	"id_token_signing_alg_values_supported": ["RS256"],
	"issuer": "https://cognito-idp.eu-west-2.amazonaws.com/REDACTED",
	"jwks_uri": "https://cognito-idp.eu-west-2.amazonaws.com/REDACTED/.well-known/jwks.json",
	"response_types_supported": ["code", "token", "token id_token"],
	"scopes_supported": ["openid", "email", "phone", "profile"],
	"subject_types_supported": ["public"],
	"token_endpoint": "https://REDACTED.auth.eu-west-2.amazoncognito.com/oauth2/token",
	"token_endpoint_auth_methods_supported": ["client_secret_basic", "client_secret_post"],
	"userinfo_endpoint": "https://REDACTED.auth.eu-west-2.amazoncognito.com/oauth2/userInfo"
}
```

**Comment by brockallen** [comment]
> Is there something that can be done to make this work?

They could implement the spec properly, or you can disable that protocol violation with this flag:

https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/DiscoveryPolicy.cs#L42

**Comment by jchannon** [comment]
Same error

Disabling this seems to sort it :)
https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/DiscoveryPolicy.cs#L47

**Comment by brockallen** [comment]
You should open an issue with them. You can refer them to the exact item in the spec: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation and let them know their implementation hurts interoperability. :)

**Comment by brockallen** [comment]
Oh sorry -- now I understand why your other flag fixed the issue. It's the endpoints, not the issuer. Ok, that's somewhat different. Sorry for my confusion.

**Comment by jchannon** [comment]
No worries.

It's working better although after login with AWS it redirects back to
localhost with a code and state querystring but in
ResponseProcessor.RedeemCodeAsync returns a TokenResponse which contains
a {"error":"invalid_client"}

Not sure how it can get that far to return that response. Not really sure
where the problem lies

**Comment by jchannon** [comment]
Ah I got it working. Needed to pass in the ClientSecret. Don't really
understand why when my JS client worked without it. Thanks again
