### ISSUE TITLE
ExpiresIn TimeSpan

### ISSUE THREAD

**Issue by alanisaac** [DuendeArchive/IdentityModel.OidcClient#82]
As a consumer that was an OIDC newbie, I hunted around a bit in the repository to make sure that the ExpiresIn parameter of RefreshTokenResult was in seconds.  It got me thinking that it might be less ambiguous and more idiomatic in c# to represent this as a TimeSpan.  I figure since the result objects already provide a bit of extra information beyond the token response objects with AccessTokenExpiration, this might be a helpful change as well:

```
/// <summary>
/// Gets or sets the expires in.
/// </summary>
/// <value>
/// The expires in.
/// </value>
public virtual TimeSpan ExpiresIn { get; internal set; }
```

**Comment by leastprivilege** [comment]
Well - `expires_in` is a protocol parameter. The lib tried to stay close to that. But I see your point.

**Comment by leastprivilege** [comment]
Will consider for v3

**Comment by leastprivilege** [comment]
There is an additional `AccessTokenExpiration` DateTime.
