### ISSUE TITLE
Invalid state in WinForms

### ISSUE THREAD

**Issue by Norrens** [DuendeArchive/IdentityModel.OidcClient#84]
Hi,
I have made two libraries to authenticate users using browser. One of them was made in WPF, but if I add reference to this library in WinForms project, then Tab or Enter button doesn't work.
To fix this I was made second .Net Framework library. I have made everything from samples.
Now I have same OidcClientOptions in both projects, but this first one (WPF) need to click buttons on page to submit form and in second (.NET) getting error "Invalid state." when I click submit button.

Where is difference between projects and how to solve invalid state?
Regards

**Comment by leastprivilege** [comment]
I don't follow. sorry.
