### ISSUE TITLE
Error : Could not load type 'IdentityModel.Client.AuthenticationStyle' from assembly 

### ISSUE THREAD

**Issue by arunprasathv** [DuendeArchive/IdentityModel.OidcClient#85]
@leastprivilege 
Getting this error in .Net 4.6.1 using IdentityModel.OidcClient # 2.8.1.   Where can i find an example for .Net 4.6.1 to use OpenID,

Getting the same error with simple instantiation.
        static void Main(string[] args)
        {
            var options = new OidcClientOptions
            {
               
            };
        }

Could not load type 'IdentityModel.Client.AuthenticationStyle' from assembly 'IdentityModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.****

![image](https://user-images.githubusercontent.com/7142390/44931963-81f32b00-ad31-11e8-8bc8-a1a8b51f9e17.png)

**Comment by leastprivilege** [comment]
This is a .NET sample

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/WindowsConsoleSystemBrowser

works for me.

**Comment by arunprasathv** [comment]
Thanks.
How do i do kerberos authentication with open id?  I'm using our coporate SSO implementation where i need to pass 
& pfidpadapterid=kerberos in the SSO request (authority) so no login page is shown. 

When hits here, never responds. just suck here, do I need to follow this implementation
 await server.WaitForConnectionAsync(token.Value)

I want to authenticate in browser, its browser based application. 

I'm looking for pure browser based solution for asp.net application? 

I see Manula and Automatic Mode here, which one i should select ?
https://github.com/IdentityModel/IdentityModel.OidcClient2

**Comment by leastprivilege** [comment]
You can pass in non-standard parameters here

https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/dev/src/IdentityModel.OidcClient/LoginRequest.cs#L36

just pass a e.g. a dictionary.

**Comment by arunprasathv** [comment]
When hits here, never responds. just suck here, do I need to follow this implementation being a browsed based application.

await server.WaitForConnectionAsync(token.Value)

I want to authenticate in browser, its browser based application., so I'm looking for pure browser based solution for asp.net application?

When I try to use this approach, get a message saying no browser configured. 

var result = await client.LoginAsync(new LoginRequest { BrowserDisplayMode = DisplayMode.Visible });

Can I use this implementaiton ?  Its in .Net Core but i need to do in .Net.
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/master/NetCoreConsoleClient/src/NetCoreConsoleClient/SystemBrowser.cs

I see Manual and Automatic Mode here, which one I should select?
https://github.com/IdentityModel/IdentityModel.OidcClient2

**Comment by leastprivilege** [comment]
I don't follow - this library is for native client applications. Not web apps.

**Comment by arunprasathv** [comment]
My requirement is to use OpenID Connect to do SSO in asp.net Web Application.

Sorry.. not getting what do you mean by native client application.

**Comment by leastprivilege** [comment]
this is not the library you are looking for. sorry.

**Comment by arunprasathv** [comment]
Ok, Is there a way to use Open ID connect to do SSO in .Net web application. most of the applications are web based that looking for SSO. wondering is there a solution.

**Comment by leastprivilege** [comment]
Sure - either use Katana or ASP.NET Core.

**Comment by arunprasathv** [comment]
something like this in asp.net core ? 
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/NetCoreConsoleClient

**Comment by leastprivilege** [comment]
OpenID Connect support is built-in in ASP.NET Core - you don't need this library.
