### ISSUE TITLE
IdentityModel.OidcClient does not have strong name

### ISSUE THREAD

**Issue by gjvdkamp** [DuendeArchive/IdentityModel.OidcClient#86]
HI, 

I just ran into the issue that the IdentityModel.OidcClient.dll in the NuGet package v2.8.1 does not have a strong name (i.e. is not signed). Is that for a reason? 

I'm using this in an app that needs signed dll's.. 

Rgds GJ

**Comment by leastprivilege** [comment]
This might happen soon ;)

**Comment by CollisionNinja** [comment]
+1
Yes please!

**Comment by leastprivilege** [comment]
Will be added in v3

**Comment by leastprivilege** [comment]
done

**Comment by sahrulijam** [comment]
will be added in v3.0.0 u mean, can u release it ealier, in 2.4.0

**Comment by sahrulijam** [comment]
2.9 i mean

**Comment by leastprivilege** [comment]
Adding a strong name is a breaking change . this will have to wait until v3 - which is soonish.

There is also a pre-release already on nuget that you can use for the time being.
