### ISSUE TITLE
Add acr_values query parameters to identity server

### ISSUE THREAD

**Issue by dharmik** [DuendeArchive/IdentityModel.OidcClient#89]
How to add **acr_values** query parameters to the identity server?

**Comment by leastprivilege** [comment]
The `LoginRequest` has an extra parameters property IIRC. That could be e.g. a dictionary.

**Comment by leastprivilege** [comment]
here 

https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/dev/src/IdentityModel.OidcClient/LoginRequest.cs#L36
