### ISSUE TITLE
unhandled exception on await client.LoginAsync(); #question

### ISSUE THREAD

**Issue by ghost** [DuendeArchive/IdentityModel.OidcClient#9]
Im getting an unhandled exception on `await client.LoginAsync();`

i used the sample of andoird Web View of https://github.com/IdentityModel/IdentityModel.OidcClient.Samples

pass a copy of my IBrowser implemented Class

```
public class SystemBrowser : IBrowser
    {
private readonly Context _context;

        //public event EventHandler<Browser> HiddenModeFailed;

        public SystemBrowser(Context context)
        {
            _context = context;
        }

        public Task<BrowserResult> InvokeAsync(BrowserOptions options)
        {
            
            var tcs = new TaskCompletionSource<BrowserResult>();

            var intent = new Intent(_context, typeof(AuthWebViewActivity));
            intent.PutExtra("ClearCookies", true);
            var state = new AuthWebViewActivity.State
            {
                Options = options
            };

            state.OnSuccess += (onj, res) =>
            {

                tcs.SetResult(new BrowserResult
                {
                    Response = res,
                    ResultType = BrowserResultType.Success
                });
            };
            intent.PutExtra("StateKey", AuthWebViewActivity.StateRepo.Add(state));

            _context.StartActivity(intent);

            return tcs.Task;
        }
```

**Comment by leastprivilege** [comment]
Well - if that is all the info you have, you need to debug it.

**Comment by ghost** [comment]
Can´t do more debug, stacktrace says an external library caused the exception

**Comment by ghost** [comment]
Callstack:
[External Code]

The las thing that debugger hits is
` state.OnSuccess += (onj, res) =>
                {


                    tcs.SetResult(new BrowserResult
                    {
                        Response = res,
                        ResultType = BrowserResultType.Success
                    });
                };`

hits the SetResult and then raise the exception.

I reach the Url and enter the credentials, May be i didnt get right the Sample be cause in the example doesnt got IBrowser interface. Do you have any docs of this?

**Comment by leastprivilege** [comment]
Sorry - don't know anything about Android - I am pretty sure your IDE must have an option to see the real exception.

**Comment by ghost** [comment]
I think maybe is the targeted api, i use the CustomTabsSample as base for my app and updated the IdentityModel.OidcClient to v2.0 (The sample has 1.0) and works!. Also i have some problems with other libraries like Xamarin.Auth with nougat api, so i think that´s the problem, Closing the issue, thanks for the reply @leastprivilege !
