### ISSUE TITLE
Plans to support 2.* version of Microsoft.Extensions.Logging library

### ISSUE THREAD

**Issue by bruno-david** [DuendeArchive/IdentityModel.OidcClient#90]
I have an issue when using a 3rd party library that references IdentityModel.OidcClient 2.7+, since my WPF app (.Net 4.7.2) has other dependencies that rely on Microsoft.Extensions.Logging 2.1.1.

When do you plan to add support to Microsoft.Extensions.Logging 2.1.1 ?

Snippet from "IdentityModel.OidcClient2/src/IdentityModel.OidcClient/IdentityModel.OidcClient.csproj"

`
  <ItemGroup Condition=" '$(TargetFramework)' == 'net452' ">
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.2" />
  </ItemGroup>
`

Or can you provide an alternative?

**Comment by leastprivilege** [comment]
Well - that would be a breaking change since it breaks everyone on 1.x

What's the issue? are there breaking changes in logging between 1 and 2?

**Comment by leastprivilege** [comment]
yes - we will drop netstandard1.x and net45x on v3
