### ISSUE TITLE
Old tokens are displayed when Refreshing in ConsoleClientWithBrowser sample

### ISSUE THREAD

**Issue by PaulRReynolds** [DuendeArchive/IdentityModel.OidcClient#91]
In the ConsoleClientWithBrowser sample, the method NextSteps allows the tokens to be refreshed (which works correctly), however the original tokens are written to the console instead of the new ones.

https://github.com/IdentityModel/IdentityModel.OidcClient2/blob/181a7f45e8d1ff890aa855d98f5f1e0230b8426f/clients/ConsoleClientWithBrowser/Program.cs#L109-L114

This should display the values of `currentAccessToken` and `currentRefreshToken`  instead.  I'd be happy to raise a pull request fixing this if you like?

**Comment by leastprivilege** [comment]
yes please!
