### ISSUE TITLE
No way of accessing BrowserResult after LogoutAsync

### ISSUE THREAD

**Issue by FinHorsley** [DuendeArchive/IdentityModel.OidcClient#94]
`public virtual async Task LogoutAsync(LogoutRequest request = null)` does not return the `BrowserResult` information returned from `InvokeAsync`. This means that there is no way to tell if the user has closed either the ` SFAuthenticationSession` or `ASWebAuthenticationSession` safari view. 

To return from the logout web page the user can either select "Click here to return to the Native Client", or press the "Cancel/Done" button. After clikcing "here", the app can pick up the redirectUrl and take the user back to a "Login Page", however if they click the "Cancel" button built into the safari webView, there is no way of knowing; the safari view just closes and the person returns to the last view. 

Solution = `public virtual async Task<BrowserResult> LogoutAsync(LogoutRequest request = null)`

**Comment by leastprivilege** [comment]
Actually - I just saw that transferring issues is now possible.

**Comment by FinHorsley** [comment]
Did i open this in IdentityModel/IdentityModel.OidcClient.Samples (first time i've opened an issue)?

Yeah an equivalent of `LoginResult` would be good, just some way to determine how the user closed the webView.

**Comment by leastprivilege** [comment]
Will be added in v3

**Comment by leastprivilege** [comment]
done

**Comment by FinHorsley** [comment]
Thanks
