### ISSUE TITLE
Endpoint is on a different host than authority

### ISSUE THREAD

**Issue by rogerskk** [DuendeArchive/IdentityModel.OidcClient#95]
I am getting the following error:
System.InvalidOperationException: Error loading discovery document: Endpoint is on a different host than authority

Is there any way to bypass this? I am using the Xamarin Forms example and my Identity server is WSO2 if that helps.  Thanks!

**Comment by leastprivilege** [comment]
You can configure that on the discovery policy (on the options).

**Comment by NitinSinghSF** [comment]
Please elaborate or provide an example
